// River job types + workers for the email channel, and the ticket.Mailer
// implementation that lets the ticket service enqueue them atomically with
// its own writes (InsertTx on the service's transaction — the property
// River was chosen for).
package email

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/riverqueue/river"

	"github.com/BryanBaluyut/slatedesk/internal/jobs"
	"github.com/BryanBaluyut/slatedesk/internal/store"
	"github.com/BryanBaluyut/slatedesk/internal/ticket"
)

// emailSendMaxAttempts bounds River's capped-backoff retries before an
// email_send job goes terminal (delivery_status='failed', visible badge).
const emailSendMaxAttempts = 8

// NotifyAssigneeArgs reasons.
const (
	NotifyReasonAssigned      = "assigned"
	NotifyReasonCustomerReply = "customer_reply"
)

// EmailSendArgs delivers one outbound article by SMTP.
type EmailSendArgs struct {
	ArticleID uuid.UUID `json:"article_id"`
	TicketID  uuid.UUID `json:"ticket_id"`
	MailboxID uuid.UUID `json:"mailbox_id"`
	// AutoGenerated marks machine-composed mail (auto-ack): loop-guard
	// headers are added so autoresponders do not answer it.
	AutoGenerated bool `json:"auto_generated"`
}

func (EmailSendArgs) Kind() string { return "email_send" }

func (EmailSendArgs) InsertOpts() river.InsertOpts {
	return river.InsertOpts{Queue: jobs.QueueEmail, MaxAttempts: emailSendMaxAttempts}
}

// AutoAckArgs composes and enqueues the auto-acknowledgement for a new
// email ticket (hardcoded behavior #1).
type AutoAckArgs struct {
	TicketID  uuid.UUID `json:"ticket_id"`
	ArticleID uuid.UUID `json:"article_id"` // the triggering inbound article
	MailboxID uuid.UUID `json:"mailbox_id"`
}

func (AutoAckArgs) Kind() string { return "email_auto_ack" }

func (AutoAckArgs) InsertOpts() river.InsertOpts {
	return river.InsertOpts{Queue: jobs.QueueEmail}
}

// NotifyAssigneeArgs emails an agent that a ticket needs their attention
// (hardcoded behavior #2): on assignment, and on a new customer article to
// an assigned ticket.
type NotifyAssigneeArgs struct {
	TicketID   uuid.UUID  `json:"ticket_id"`
	AssigneeID uuid.UUID  `json:"assignee_id"`
	ArticleID  *uuid.UUID `json:"article_id,omitempty"`
	Reason     string     `json:"reason"`
	// ActorID caused the event; the worker never notifies the actor about
	// their own action (double-checked here and at enqueue time).
	ActorID *uuid.UUID `json:"actor_id,omitempty"`
	// MessageID is the outbound Message-ID's local part, minted at ENQUEUE
	// time so every River redelivery of this job reuses the same id — a
	// crash-after-SMTP-accept retry then sends a duplicate the agent's MUA
	// collapses instead of a second distinct notification, and failed
	// attempts stop accreting never-sent ids into the References chain.
	// The sending domain is appended at send time (the mailbox is resolved
	// in the worker). Empty (a job enqueued before this field existed)
	// falls back to a per-attempt id.
	MessageID string `json:"message_id,omitempty"`
}

func (NotifyAssigneeArgs) Kind() string { return "email_notify_assignee" }

func (NotifyAssigneeArgs) InsertOpts() river.InsertOpts {
	return river.InsertOpts{Queue: jobs.QueueEmail}
}

// RegisterWorkers registers the email workers on reg. Call before
// jobs.NewClient; then hand the client back via Engine.SetRiver.
func RegisterWorkers(reg *jobs.Registry, e *Engine) error {
	if err := jobs.AddWorker(reg, &EmailSendWorker{engine: e}); err != nil {
		return err
	}
	if err := jobs.AddWorker(reg, &AutoAckWorker{engine: e}); err != nil {
		return err
	}
	if err := jobs.AddWorker(reg, &NotifyAssigneeWorker{engine: e}); err != nil {
		return err
	}
	return nil
}

// EmailSendWorker drives Engine.BuildAndSend. River retries errors with
// capped backoff; the final failed attempt flips the article to the
// terminal 'failed' badge.
type EmailSendWorker struct {
	river.WorkerDefaults[EmailSendArgs]
	engine *Engine
}

func (w *EmailSendWorker) Work(ctx context.Context, job *river.Job[EmailSendArgs]) error {
	err := w.engine.BuildAndSend(ctx, job.Args.ArticleID, job.Args.MailboxID, job.Args.AutoGenerated)
	if err == nil {
		return nil
	}
	if job.Attempt >= job.MaxAttempts {
		slog.Error("email: send exhausted retries; marking failed",
			"article_id", job.Args.ArticleID, "attempts", job.Attempt, "error", err)
		if mfErr := w.engine.MarkSendFailed(ctx, job.Args.ArticleID); mfErr != nil {
			slog.Error("email: could not mark article failed", "article_id", job.Args.ArticleID, "error", mfErr)
		}
	}
	return err
}

// AutoAckWorker composes the acknowledgement article (sender_type=system,
// fixed template with the ticket number) and enqueues its email_send in
// the SAME transaction.
//
// Loop guards, in order: the inbound pipeline never enqueues this job for
// suppress-flagged mail (autoresponders) — that decision is transactional
// with the ingest; the ack itself goes out with Auto-Submitted:
// auto-replied + X-Auto-Response-Suppress (AutoGenerated=true), so a
// remote autoresponder answering it is suppressed on ITS side and caught
// by OUR loop guard if it answers anyway ("never ack an ack"); and a
// has-ack re-check makes a River redelivery of this job a no-op.
//
// Backscatter (deliberate, documented): like every helpdesk autoresponder,
// the ack necessarily goes to the unauthenticated From address — M3 does
// no SPF/DKIM verification — so a spoofed sender can direct one
// helpdesk-branded ack per inbound message at a victim address, with the
// echoed subject as the only attacker-influenced text. Bounded by: the
// loop guard (declared machine mail is never acked), one ack per ticket,
// the subject echo truncated below, and the per-mailbox auto_ack_enabled
// kill switch. Sender authentication (SPF/DKIM/ARC) is a post-M3
// hardening candidate.
type AutoAckWorker struct {
	river.WorkerDefaults[AutoAckArgs]
	engine *Engine
}

func (w *AutoAckWorker) Work(ctx context.Context, job *river.Job[AutoAckArgs]) error {
	e := w.engine

	trigger, err := e.q.GetArticle(ctx, job.Args.ArticleID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil // ticket/article deleted since; nothing to ack
		}
		return fmt.Errorf("email: auto-ack load trigger article: %w", err)
	}
	// Belt-and-braces: only customer mail is ever acked.
	if trigger.SenderType != store.ArticleSenderCustomer {
		return nil
	}

	t, err := e.q.GetTicket(ctx, job.Args.TicketID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}
		return fmt.Errorf("email: auto-ack load ticket: %w", err)
	}

	// The subject is untrusted inbound text reflected to an unverified
	// address (see the backscatter note above): truncate so the echo can
	// carry at most one line's worth of attacker-chosen content.
	subject := t.Ticket.Subject
	if r := []rune(subject); len(r) > 200 {
		subject = string(r[:200]) + "…"
	}
	body := fmt.Sprintf(
		"Hello %s,\n\n"+
			"we received your request and created ticket [SD-%s] for it.\n\n"+
			"Subject: %s\n\n"+
			"We will get back to you as soon as possible. Replying to this "+
			"email adds to the same ticket.\n",
		t.RequesterName, t.Ticket.Number, subject)

	err = e.inTx(ctx, func(q *store.Queries, tx pgx.Tx) error {
		// Idempotency: a crash after this tx committed but before River
		// acked the job must not produce a second ack on redelivery.
		hasAck, err := q.TicketHasSystemEmailArticle(ctx, t.Ticket.ID)
		if err != nil {
			return fmt.Errorf("check existing ack: %w", err)
		}
		if hasAck {
			return nil
		}

		ack, err := q.CreateArticle(ctx, store.CreateArticleParams{
			TicketID:   t.Ticket.ID,
			SenderType: store.ArticleSenderSystem,
			Channel:    store.ArticleChannelEmail,
			IsInternal: false,
			BodyText:   body,
		})
		if err != nil {
			return fmt.Errorf("insert ack article: %w", err)
		}
		if _, err := q.SetArticleDeliveryStatus(ctx, store.SetArticleDeliveryStatusParams{
			ID:             ack.ID,
			DeliveryStatus: pgtype.Text{String: DeliveryQueued, Valid: true},
		}); err != nil {
			return fmt.Errorf("mark ack queued: %w", err)
		}
		if err := addTicketEvent(ctx, q, t.Ticket.ID, nil, ticket.EventArticleAdded, map[string]any{
			"article_id":  ack.ID,
			"sender_type": store.ArticleSenderSystem,
			"is_internal": false,
			"auto_ack":    true,
		}); err != nil {
			return err
		}
		if e.river == nil {
			return errors.New("email: river client not wired")
		}
		if _, err := e.river.InsertTx(ctx, tx, EmailSendArgs{
			ArticleID:     ack.ID,
			TicketID:      t.Ticket.ID,
			MailboxID:     job.Args.MailboxID,
			AutoGenerated: true,
		}, nil); err != nil {
			return fmt.Errorf("enqueue ack send: %w", err)
		}
		return notifyTx(ctx, tx, ticket.NotifyArticleCreated, t.Ticket.ID)
	})
	if err != nil {
		return fmt.Errorf("email: auto-ack for ticket %s: %w", t.Ticket.Number, err)
	}
	return nil
}

// NotifyAssigneeWorker emails the assignee directly (no article). The
// notification threads into the ticket conversation (recorded outbound
// Message-ID + References + subject token) so a reply from the agent's
// MUA lands on the ticket.
type NotifyAssigneeWorker struct {
	river.WorkerDefaults[NotifyAssigneeArgs]
	engine *Engine
}

func (w *NotifyAssigneeWorker) Work(ctx context.Context, job *river.Job[NotifyAssigneeArgs]) error {
	e := w.engine
	a := job.Args

	if a.ActorID != nil && *a.ActorID == a.AssigneeID {
		return nil // never notify the actor about their own action
	}

	t, err := e.q.GetTicket(ctx, a.TicketID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}
		return fmt.Errorf("email: notify load ticket: %w", err)
	}
	// Reassigned (or unassigned) since enqueue: stale, drop.
	if !t.Ticket.AssigneeID.Valid || uuid.UUID(t.Ticket.AssigneeID.Bytes) != a.AssigneeID {
		return nil
	}
	assignee, err := e.q.GetUserByID(ctx, a.AssigneeID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil
		}
		return fmt.Errorf("email: notify load assignee: %w", err)
	}
	if !assignee.Active {
		return nil
	}

	mb, err := e.notifyMailbox(ctx, t.Ticket.ID)
	if err != nil {
		if errors.Is(err, errNotEmailTicket) {
			slog.Info("email: no mailbox available for assignee notification; skipping",
				"ticket", t.Ticket.Number, "assignee", assignee.Email)
			return nil
		}
		return err
	}

	var body string
	switch a.Reason {
	case NotifyReasonCustomerReply:
		body = fmt.Sprintf("Hello %s,\n\nticket [SD-%s] (%s) assigned to you has a new customer reply.\n",
			assignee.Name, t.Ticket.Number, t.Ticket.Subject)
	default:
		body = fmt.Sprintf("Hello %s,\n\nticket [SD-%s] (%s) has been assigned to you.\n",
			assignee.Name, t.Ticket.Number, t.Ticket.Subject)
	}

	if err := e.sendNotification(ctx, mb, t, assignee.Name, assignee.Email, body, a.MessageID); err != nil {
		return err
	}
	return nil
}

// notifyMailbox picks the sending mailbox for a notification: the ticket's
// email-origin mailbox, else any active mailbox (notifications also fire
// for web/api tickets), else errNotEmailTicket.
func (e *Engine) notifyMailbox(ctx context.Context, ticketID uuid.UUID) (store.Mailbox, error) {
	mb, err := e.q.LatestInboundMailboxForTicket(ctx, ticketID)
	if err == nil {
		return mb, nil
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return store.Mailbox{}, fmt.Errorf("email: origin mailbox for %s: %w", ticketID, err)
	}
	boxes, err := e.q.ListActiveMailboxes(ctx)
	if err != nil {
		return store.Mailbox{}, fmt.Errorf("email: list active mailboxes: %w", err)
	}
	if len(boxes) == 0 {
		return store.Mailbox{}, errNotEmailTicket
	}
	return boxes[0], nil
}

// --- ticket.Mailer implementation -------------------------------------------

// Engine implements ticket.Mailer so the ticket service can hand outbound
// work to the email channel inside its OWN transactions.
var _ ticket.Mailer = (*Engine)(nil)

// EnqueueAgentReply is called by the ticket service inside the AddArticle
// transaction for every public agent reply. If the ticket has an email
// origin (an inbound email_message_ids row), the article is marked
// 'queued' and an email_send job is inserted ON THE SAME pgx.Tx — the
// reply and its delivery job commit or roll back together. Non-email
// tickets are untouched (no-op), so web/api flows behave exactly as in M2.
func (e *Engine) EnqueueAgentReply(ctx context.Context, tx pgx.Tx, ticketID, articleID uuid.UUID) error {
	if e.river == nil {
		return errors.New("email: river client not wired")
	}
	q := store.New(tx)
	mb, err := q.LatestInboundMailboxForTicket(ctx, ticketID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil // not an email-origin ticket
		}
		return fmt.Errorf("email: resolve reply mailbox: %w", err)
	}
	if _, err := q.SetArticleDeliveryStatus(ctx, store.SetArticleDeliveryStatusParams{
		ID:             articleID,
		DeliveryStatus: pgtype.Text{String: DeliveryQueued, Valid: true},
	}); err != nil {
		return fmt.Errorf("email: mark reply queued: %w", err)
	}
	if _, err := e.river.InsertTx(ctx, tx, EmailSendArgs{
		ArticleID: articleID,
		TicketID:  ticketID,
		MailboxID: mb.ID,
	}, nil); err != nil {
		return fmt.Errorf("email: enqueue reply send: %w", err)
	}
	return nil
}

// EnqueueAssigneeNotify is called by the ticket service inside the
// assignment transaction. Self-assignment never notifies.
func (e *Engine) EnqueueAssigneeNotify(ctx context.Context, tx pgx.Tx, ticketID, assigneeID uuid.UUID, actorID *uuid.UUID) error {
	if e.river == nil {
		return errors.New("email: river client not wired")
	}
	if actorID != nil && *actorID == assigneeID {
		return nil
	}
	if _, err := e.river.InsertTx(ctx, tx, NotifyAssigneeArgs{
		TicketID:   ticketID,
		AssigneeID: assigneeID,
		Reason:     NotifyReasonAssigned,
		ActorID:    actorID,
		MessageID:  uuid.NewString(),
	}, nil); err != nil {
		return fmt.Errorf("email: enqueue assignee notification: %w", err)
	}
	return nil
}
