// Outbound pipeline (architecture doc §4): the article INSERT and its
// email_send job commit atomically (ticket.Mailer / inbound enqueues); this
// file is the send side that the EmailSendWorker drives.
//
// Ordering invariant: the outbound Message-ID is generated under the
// mailbox's domain and committed to email_message_ids (and the article row,
// delivery_status='sending') BEFORE the SMTP dial. A reply from the
// customer can therefore always be threaded — even if we crash between
// send and the 'sent' status write.
//
// Residual double-send window (documented, accepted): if the process dies
// after the SMTP server accepts the message but before River records the
// job as complete, the retry sends the message again. The retry reuses the
// SAME Message-ID (it was committed pre-send), so receiving MTAs/MUAs
// collapse the duplicate; the alternative — marking 'sent' before the SMTP
// dial — would silently LOSE mail on a crash-pre-send, which is strictly
// worse for a help desk. Exactly-once email does not exist; at-least-once
// with a stable Message-ID is the correct trade.
package email

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"html"
	"io"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/wneessen/go-mail"

	"github.com/BryanBaluyut/slatedesk/internal/store"
	"github.com/BryanBaluyut/slatedesk/internal/ticket"
)

// Article delivery_status values (text column; the badge states).
const (
	DeliveryQueued  = "queued"
	DeliverySending = "sending"
	DeliverySent    = "sent"
	DeliveryFailed  = "failed"
)

// maxReferences caps the References header chain (RFC 5322 suggests
// trimming; 20 ids keep the header well under transport limits).
const maxReferences = 20

// BuildAndSend delivers the outbound article articleID through mailboxID.
// autoGenerated adds the loop-guard headers (auto-ack and any other
// machine-composed article); agent replies do NOT carry them — a human
// wrote the content, and downstream autoresponders are allowed to answer
// a human.
//
// Idempotency: if the article's delivery_status is already 'sent' this is
// a no-op — the safety net for River retrying a job whose process crashed
// after the 'sent' commit but before the job was acked.
func (e *Engine) BuildAndSend(ctx context.Context, articleID, mailboxID uuid.UUID, autoGenerated bool) error {
	article, err := e.q.GetArticle(ctx, articleID)
	if err != nil {
		return fmt.Errorf("email: load outbound article %s: %w", articleID, err)
	}
	if article.DeliveryStatus.Valid && article.DeliveryStatus.String == DeliverySent {
		return nil // already delivered; crash-window retry
	}

	t, err := e.q.GetTicket(ctx, article.TicketID)
	if err != nil {
		return fmt.Errorf("email: load ticket %s: %w", article.TicketID, err)
	}
	mb, err := e.q.GetMailbox(ctx, mailboxID)
	if err != nil {
		return fmt.Errorf("email: load mailbox %s: %w", mailboxID, err)
	}

	// Reuse the Message-ID committed by an earlier attempt; mint otherwise.
	msgID := ""
	if article.MessageID.Valid {
		msgID = article.MessageID.String
	} else {
		msgID = uuid.NewString() + "@" + mailboxDomain(mb)
	}

	inReplyTo, references, err := e.threadHeaders(ctx, t.Ticket.ID, msgID)
	if err != nil {
		return err
	}

	// Commit Message-ID + 'sending' BEFORE the SMTP dial (see file doc).
	err = e.inTx(ctx, func(q *store.Queries, tx pgx.Tx) error {
		if _, err := q.SetArticleEmailMeta(ctx, store.SetArticleEmailMetaParams{
			ID:               article.ID,
			MessageID:        pgtype.Text{String: msgID, Valid: true},
			InReplyTo:        textOrNull(inReplyTo),
			ReferencesHeader: textOrNull(strings.Join(references, " ")),
			DeliveryStatus:   pgtype.Text{String: DeliverySending, Valid: true},
		}); err != nil {
			return fmt.Errorf("stamp outbound meta: %w", err)
		}
		// ON CONFLICT DO NOTHING: on a retry the row is already ours.
		if _, err := q.InsertEmailMessageID(ctx, store.InsertEmailMessageIDParams{
			MessageID: msgID,
			Direction: store.EmailDirectionOutbound,
			MailboxID: pgtype.UUID{Bytes: mb.ID, Valid: true},
			TicketID:  t.Ticket.ID,
			ArticleID: pgtype.UUID{Bytes: article.ID, Valid: true},
		}); err != nil {
			return fmt.Errorf("record outbound message id: %w", err)
		}
		// The queued -> sending transition is a delivery badge change like
		// any other: the API contract promises an article.updated stream
		// event for EVERY transition, and without it the 'sending' state
		// is invisible to a watching workspace until sent/failed lands.
		return notifyTx(ctx, tx, ticket.NotifyArticleUpdated, t.Ticket.ID)
	})
	if err != nil {
		return fmt.Errorf("email: pre-send commit for article %s: %w", article.ID, err)
	}

	msg, err := e.buildMessage(ctx, buildParams{
		mb:            mb,
		toName:        t.RequesterName,
		toAddr:        t.RequesterEmail,
		subject:       replySubject(t.Ticket),
		msgID:         msgID,
		inReplyTo:     inReplyTo,
		references:    references,
		bodyText:      article.BodyText,
		bodyHTML:      article.BodyHtml.String,
		autoGenerated: autoGenerated,
		attachments:   article.ID,
	})
	if err != nil {
		return err
	}

	if err := e.smtpSend(ctx, mb, msg); err != nil {
		return fmt.Errorf("email: send article %s via %s: %w", article.ID, mb.EmailAddress, err)
	}

	return e.setDeliveryStatus(ctx, article.ID, t.Ticket.ID, DeliverySent)
}

// ErrRetryNotFailed is returned by RetryFailedSend when the article's
// delivery is not retryable: any status other than the terminal 'failed',
// with one exception — a 'sending' article whose send job no longer exists
// (the stuck-badge crash window, see RetryFailedSend) is retryable, while
// a send genuinely in flight is not. The HTTP layer maps it to 409.
var ErrRetryNotFailed = errors.New("email: article delivery status is not failed")

// ErrRetryNoMailbox is returned by RetryFailedSend when no mailbox can be
// resolved to deliver the article (e.g. the origin mailbox was deleted).
var ErrRetryNoMailbox = errors.New("email: no mailbox available to deliver this article")

// RetryFailedSend re-enqueues delivery of a dead outbound article (POST
// /articles/{id}/retry-send): delivery_status flips back to 'queued' and
// the email_send job is inserted in the SAME transaction — transactional
// enqueue, like every other outbound path. "Dead" means terminally
// 'failed', or stuck on 'sending' with no live send job left (the
// crash-during-final-attempt window; see the status switch below). The
// retried send reuses the Message-ID committed before the first attempt
// (BuildAndSend finds it on the article row), so a duplicate delivery can
// never fork the thread. The status flip is guarded by a status
// predicate, so a concurrent retry gets ErrRetryNotFailed instead of a
// duplicate job.
func (e *Engine) RetryFailedSend(ctx context.Context, articleID uuid.UUID) (store.Article, error) {
	if e.river == nil {
		return store.Article{}, errors.New("email: river client not wired")
	}
	article, err := e.q.GetArticle(ctx, articleID)
	if err != nil {
		return store.Article{}, fmt.Errorf("email: load article %s for retry: %w", articleID, err)
	}
	switch {
	case article.DeliveryStatus.Valid && article.DeliveryStatus.String == DeliveryFailed:
		// The terminal badge — the normal retry case.
	case article.DeliveryStatus.Valid && article.DeliveryStatus.String == DeliverySending:
		// Normally in flight — but a crash during the FINAL send attempt
		// leaves the badge stuck on 'sending' forever: River's rescuer
		// discards the exhausted job WITHOUT re-running the worker, so
		// neither the 'sent' write nor MarkSendFailed ever happens. Allow
		// the retry exactly when no live email_send job exists for the
		// article; a genuinely in-flight send still answers 409. Worst
		// case (the job finishes between this check and the status flip)
		// is a duplicate delivery with the SAME pre-committed Message-ID —
		// the documented at-least-once trade.
		live, err := e.hasLiveSendJob(ctx, articleID)
		if err != nil {
			return store.Article{}, err
		}
		if live {
			return store.Article{}, ErrRetryNotFailed
		}
	default:
		return store.Article{}, ErrRetryNotFailed
	}

	mb, err := e.retryMailbox(ctx, article)
	if err != nil {
		return store.Article{}, err
	}

	var updated store.Article
	err = e.inTx(ctx, func(q *store.Queries, tx pgx.Tx) error {
		updated, err = q.MarkFailedArticleQueued(ctx, articleID)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return ErrRetryNotFailed // raced another retry or a late success
			}
			return fmt.Errorf("mark article queued: %w", err)
		}
		if _, err := e.river.InsertTx(ctx, tx, EmailSendArgs{
			ArticleID: articleID,
			TicketID:  article.TicketID,
			MailboxID: mb.ID,
			// System-authored mail (the auto-ack) keeps its loop-guard
			// headers on the retried delivery.
			AutoGenerated: article.SenderType == store.ArticleSenderSystem,
		}, nil); err != nil {
			return fmt.Errorf("enqueue retried send: %w", err)
		}
		return notifyTx(ctx, tx, ticket.NotifyArticleUpdated, article.TicketID)
	})
	if err != nil {
		if errors.Is(err, ErrRetryNotFailed) {
			return store.Article{}, ErrRetryNotFailed
		}
		return store.Article{}, fmt.Errorf("email: retry send for article %s: %w", articleID, err)
	}
	return updated, nil
}

// hasLiveSendJob reports whether a not-yet-finished email_send job exists
// for the article. Raw SQL (not sqlc): river_job is created by River's
// runtime migrations, so sqlc's schema does not know the table.
func (e *Engine) hasLiveSendJob(ctx context.Context, articleID uuid.UUID) (bool, error) {
	var live bool
	if err := e.pool.QueryRow(ctx, `
		SELECT EXISTS (
			SELECT 1 FROM river_job
			WHERE kind = 'email_send'
			  AND state IN ('available', 'pending', 'retryable', 'running', 'scheduled')
			  AND args->>'article_id' = $1)`,
		articleID.String()).Scan(&live); err != nil {
		return false, fmt.Errorf("email: check live send job for article %s: %w", articleID, err)
	}
	return live, nil
}

// retryMailbox resolves the mailbox a retried send goes out through: the
// mailbox recorded with the article's committed outbound Message-ID when
// available (the first attempt reached the pre-send commit), otherwise
// the ticket's email-origin mailbox — the same choice EnqueueAgentReply
// made originally.
func (e *Engine) retryMailbox(ctx context.Context, article store.Article) (store.Mailbox, error) {
	if article.MessageID.Valid {
		row, err := e.q.GetEmailMessageID(ctx, article.MessageID.String)
		switch {
		case err == nil && row.MailboxID.Valid:
			mb, err := e.q.GetMailbox(ctx, uuid.UUID(row.MailboxID.Bytes))
			if err == nil {
				return mb, nil
			}
			if !errors.Is(err, pgx.ErrNoRows) {
				return store.Mailbox{}, fmt.Errorf("email: load retry mailbox: %w", err)
			}
			// Mailbox deleted since; fall through to the origin lookup.
		case err != nil && !errors.Is(err, pgx.ErrNoRows):
			return store.Mailbox{}, fmt.Errorf("email: look up outbound message id: %w", err)
		}
	}
	mb, err := e.q.LatestInboundMailboxForTicket(ctx, article.TicketID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return store.Mailbox{}, ErrRetryNoMailbox
		}
		return store.Mailbox{}, fmt.Errorf("email: resolve retry mailbox: %w", err)
	}
	return mb, nil
}

// MarkSendFailed is the terminal-failure path: River exhausted its retries.
// The article gets the visible 'failed' badge.
func (e *Engine) MarkSendFailed(ctx context.Context, articleID uuid.UUID) error {
	article, err := e.q.GetArticle(ctx, articleID)
	if err != nil {
		return fmt.Errorf("email: load article %s for failure mark: %w", articleID, err)
	}
	if article.DeliveryStatus.Valid && article.DeliveryStatus.String == DeliverySent {
		return nil // raced a success; keep 'sent'
	}
	return e.setDeliveryStatus(ctx, articleID, article.TicketID, DeliveryFailed)
}

// setDeliveryStatus commits a delivery badge transition + the SSE hint.
func (e *Engine) setDeliveryStatus(ctx context.Context, articleID, ticketID uuid.UUID, status string) error {
	err := e.inTx(ctx, func(q *store.Queries, tx pgx.Tx) error {
		if _, err := q.SetArticleDeliveryStatus(ctx, store.SetArticleDeliveryStatusParams{
			ID:             articleID,
			DeliveryStatus: pgtype.Text{String: status, Valid: true},
		}); err != nil {
			return fmt.Errorf("set delivery status %s: %w", status, err)
		}
		return notifyTx(ctx, tx, ticket.NotifyArticleUpdated, ticketID)
	})
	if err != nil {
		return fmt.Errorf("email: article %s -> %s: %w", articleID, status, err)
	}
	return nil
}

// sendNotification delivers a machine-generated, non-article mail (the
// notify-assignee behavior). Its Message-ID is still recorded in
// email_message_ids (article NULL) BEFORE the send, so an agent replying
// to the notification from their MUA threads straight into the ticket.
//
// msgIDLocal is the id's local part, minted at ENQUEUE time (see
// NotifyAssigneeArgs.MessageID) so a River redelivery reuses the same
// Message-ID and MUAs collapse the duplicate — the same crash-window trade
// BuildAndSend makes with its pre-committed id. Empty (a job from before
// the field existed) falls back to a per-attempt id.
func (e *Engine) sendNotification(ctx context.Context, mb store.Mailbox, t store.GetTicketRow, toName, toAddr, bodyText, msgIDLocal string) error {
	if msgIDLocal == "" {
		msgIDLocal = uuid.NewString()
	}
	msgID := msgIDLocal + "@" + mailboxDomain(mb)
	inReplyTo, references, err := e.threadHeaders(ctx, t.Ticket.ID, msgID)
	if err != nil {
		return err
	}
	err = e.inTx(ctx, func(q *store.Queries, tx pgx.Tx) error {
		if _, err := q.InsertEmailMessageID(ctx, store.InsertEmailMessageIDParams{
			MessageID: msgID,
			Direction: store.EmailDirectionOutbound,
			MailboxID: pgtype.UUID{Bytes: mb.ID, Valid: true},
			TicketID:  t.Ticket.ID,
		}); err != nil {
			return fmt.Errorf("record notification message id: %w", err)
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("email: pre-send commit for notification: %w", err)
	}

	msg, err := e.buildMessage(ctx, buildParams{
		mb:            mb,
		toName:        toName,
		toAddr:        toAddr,
		subject:       replySubject(t.Ticket),
		msgID:         msgID,
		inReplyTo:     inReplyTo,
		references:    references,
		bodyText:      bodyText,
		autoGenerated: true,
	})
	if err != nil {
		return err
	}
	if err := e.smtpSend(ctx, mb, msg); err != nil {
		return fmt.Errorf("email: send notification via %s: %w", mb.EmailAddress, err)
	}
	return nil
}

// buildParams collects everything buildMessage needs.
type buildParams struct {
	mb             store.Mailbox
	toName, toAddr string
	subject        string
	msgID          string
	inReplyTo      string
	references     []string
	bodyText       string
	bodyHTML       string
	autoGenerated  bool
	attachments    uuid.UUID // article id to attach files from; zero = none
}

// buildMessage constructs the go-mail message: headers, threading, subject
// token, signature, loop-guard headers, attachments.
func (e *Engine) buildMessage(ctx context.Context, p buildParams) (*mail.Msg, error) {
	m := mail.NewMsg()
	fromName := p.mb.FromDisplayName
	if fromName == "" {
		fromName = p.mb.Name
	}
	if err := m.FromFormat(fromName, p.mb.EmailAddress); err != nil {
		return nil, fmt.Errorf("email: bad from address %q: %w", p.mb.EmailAddress, err)
	}
	if err := m.AddToFormat(p.toName, p.toAddr); err != nil {
		return nil, fmt.Errorf("email: bad recipient address %q: %w", p.toAddr, err)
	}
	m.Subject(p.subject)
	m.SetMessageIDWithValue(p.msgID) // wraps in <>

	if p.inReplyTo != "" {
		m.SetGenHeader(mail.HeaderInReplyTo, "<"+p.inReplyTo+">")
	}
	if len(p.references) > 0 {
		bracketed := make([]string, len(p.references))
		for i, id := range p.references {
			bracketed[i] = "<" + id + ">"
		}
		m.SetGenHeader(mail.HeaderReferences, strings.Join(bracketed, " "))
	}

	// Loop guard on machine-generated mail (auto-ack, notifications):
	// receiving autoresponders stay quiet, and our own inbound loop guard
	// recognizes the mail if it ever bounces back (never ack an ack).
	if p.autoGenerated {
		m.SetGenHeader("Auto-Submitted", "auto-replied")
		m.SetGenHeader("X-Auto-Response-Suppress", "All")
	}

	text := p.bodyText
	if sig := strings.TrimSpace(p.mb.Signature); sig != "" {
		text += "\n\n-- \n" + sig
	}
	m.SetBodyString(mail.TypeTextPlain, text)

	if strings.TrimSpace(p.bodyHTML) != "" {
		htmlBody := p.bodyHTML
		if sig := strings.TrimSpace(p.mb.Signature); sig != "" {
			htmlBody += "<br><br>-- <br>" + strings.ReplaceAll(html.EscapeString(sig), "\n", "<br>")
		}
		m.AddAlternativeString(mail.TypeTextHTML, htmlBody)
	}

	if p.attachments != uuid.Nil {
		atts, err := e.q.ListArticleAttachments(ctx, p.attachments)
		if err != nil {
			return nil, fmt.Errorf("email: list attachments for article %s: %w", p.attachments, err)
		}
		for _, att := range atts {
			rc, err := e.blobs.Open(ctx, att.StorageKey)
			if err != nil {
				return nil, fmt.Errorf("email: open attachment blob %s: %w", att.StorageKey, err)
			}
			data, err := io.ReadAll(rc)
			_ = rc.Close()
			if err != nil {
				return nil, fmt.Errorf("email: read attachment blob %s: %w", att.StorageKey, err)
			}
			if err := m.AttachReader(att.Filename, bytes.NewReader(data),
				mail.WithFileContentType(mail.ContentType(att.ContentType))); err != nil {
				return nil, fmt.Errorf("email: attach %q: %w", att.Filename, err)
			}
		}
	}
	return m, nil
}

// smtpSend dials per the mailbox's TLS mode + auth kind and sends.
func (e *Engine) smtpSend(ctx context.Context, mb store.Mailbox, msg *mail.Msg) error {
	opts := []mail.Option{mail.WithPort(int(mb.SmtpPort))}
	opts = append(opts, smtpTLSOptions(mb.SmtpTlsMode)...)
	authOpts, err := e.auth.SMTPOptions(ctx, mb)
	if err != nil {
		return err
	}
	opts = append(opts, authOpts...)

	client, err := mail.NewClient(mb.SmtpHost, opts...)
	if err != nil {
		return fmt.Errorf("smtp client: %w", err)
	}
	if err := client.DialAndSendWithContext(ctx, msg); err != nil {
		return fmt.Errorf("smtp send: %w", err)
	}
	return nil
}

// threadHeaders derives In-Reply-To (the latest inbound Message-ID) and
// the References chain (oldest-first, capped, excluding selfID) for a
// ticket.
func (e *Engine) threadHeaders(ctx context.Context, ticketID uuid.UUID, selfID string) (inReplyTo string, references []string, err error) {
	latest, err := e.q.LatestInboundMessageIDForTicket(ctx, ticketID)
	switch {
	case err == nil:
		inReplyTo = latest.MessageID
	case errors.Is(err, pgx.ErrNoRows):
		// No inbound mail yet (agent-initiated or notification on a
		// non-email ticket): plain References-less mail.
	default:
		return "", nil, fmt.Errorf("email: latest inbound id for %s: %w", ticketID, err)
	}

	rows, err := e.q.ListRecentEmailMessageIDsByTicket(ctx, store.ListRecentEmailMessageIDsByTicketParams{
		TicketID: ticketID,
		Limit:    maxReferences,
	})
	if err != nil {
		return "", nil, fmt.Errorf("email: reference chain for %s: %w", ticketID, err)
	}
	// Newest-first from the query; the header wants oldest-first.
	for i := len(rows) - 1; i >= 0; i-- {
		if rows[i].MessageID == selfID {
			continue
		}
		references = append(references, rows[i].MessageID)
	}
	return inReplyTo, references, nil
}

// replySubject renders "Re: <subject> [SD-<number>]" — the token is the
// subject-fallback threading anchor. Any token already inside the stored
// subject is stripped first so it never doubles.
func replySubject(t store.Ticket) string {
	subject := strings.TrimSpace(ticketTokenRe.ReplaceAllString(t.Subject, ""))
	return "Re: " + subject + " [SD-" + t.Number + "]"
}
