#!/bin/sh
# SlateDesk v2 installer — the `curl -fsSL https://get.slatedesk.io | sh`
# onboarding path (architecture doc §5). It writes a docker-compose.yml and a
# .env with a freshly generated POSTGRES_PASSWORD, brings the stack up, waits
# for the app to answer, and tells you where to find the one-time setup URL.
#
# Safe to re-run: an existing .env (and its generated password) is preserved,
# and an existing compose file is left untouched. Configurable via env vars:
#
#   SLATEDESK_DIR    install directory        (default: ./slatedesk)
#   SLATEDESK_IMAGE  pinned app image tag     (default: the version below)
#   SLATEDESK_PORT   host port for the app    (default: 8000)
#
# POSIX sh; no bashisms. Shellcheck-clean.
set -eu

# --- pinned versions (bump deliberately) ------------------------------------
DEFAULT_IMAGE="ghcr.io/bryanbaluyut/slatedesk:2.0-beta"

DIR="${SLATEDESK_DIR:-./slatedesk}"
IMAGE="${SLATEDESK_IMAGE:-$DEFAULT_IMAGE}"
PORT="${SLATEDESK_PORT:-8000}"

info() { printf '\033[1;36m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$1" >&2; }
err()  { printf '\033[1;31merror:\033[0m %s\n' "$1" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# --- preflight: docker + compose --------------------------------------------
have docker || err "docker is not installed — see https://docs.docker.com/engine/install/"
docker info >/dev/null 2>&1 || err "the docker daemon is not reachable (is it running? do you have permission?)"

if docker compose version >/dev/null 2>&1; then
	COMPOSE="docker compose"
elif have docker-compose; then
	COMPOSE="docker-compose"
else
	err "docker compose is not available — install the Compose plugin (https://docs.docker.com/compose/install/)"
fi
info "using: $COMPOSE"

# --- a strong POSTGRES_PASSWORD ---------------------------------------------
gen_secret() {
	if have openssl; then
		openssl rand -hex 24
	elif [ -r /dev/urandom ]; then
		# 48 hex chars (~192 bits) without openssl.
		LC_ALL=C tr -dc 'a-f0-9' </dev/urandom | dd bs=1 count=48 2>/dev/null
	else
		err "cannot generate a password: no openssl and no /dev/urandom"
	fi
}

# --- write the install directory --------------------------------------------
mkdir -p "$DIR"
cd "$DIR"
info "install directory: $(pwd)"

if [ -f .env ]; then
	info ".env already exists — keeping the existing password"
else
	PW="$(gen_secret)"
	[ -n "$PW" ] || err "generated an empty password"
	umask 077
	{
		printf 'POSTGRES_PASSWORD=%s\n' "$PW"
		printf 'SLATEDESK_IMAGE=%s\n' "$IMAGE"
		printf 'SLATEDESK_PORT=%s\n' "$PORT"
	} >.env
	info "wrote .env (generated POSTGRES_PASSWORD)"
fi

if [ -f docker-compose.yml ]; then
	info "docker-compose.yml already exists — leaving it untouched"
else
	# Quoted heredoc: everything is literal. ${...} is resolved by Compose
	# from .env at runtime, not by this shell.
	cat >docker-compose.yml <<'EOF'
# SlateDesk v2 — single-node stack, generated by install.sh.
# The app image and password come from the sibling .env file.
name: slatedesk

services:
  app:
    image: ${SLATEDESK_IMAGE:?set SLATEDESK_IMAGE in .env}
    restart: unless-stopped
    ports:
      - "${SLATEDESK_PORT:-8000}:8000"
    environment:
      DATABASE_URL: postgres://slatedesk:${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}@postgres:5432/slatedesk?sslmode=disable
      SLATEDESK_DATA_DIR: /data
    volumes:
      - attachments:/data
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: slatedesk
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: slatedesk
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slatedesk -d slatedesk"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

volumes:
  pgdata:
  attachments:
EOF
	info "wrote docker-compose.yml (image pinned in .env)"
fi

# --- pull + up --------------------------------------------------------------
info "pulling image ($IMAGE) ..."
# $COMPOSE is "docker compose" (two words) or "docker-compose"; the split is
# intentional.
# shellcheck disable=SC2086
$COMPOSE pull >/dev/null 2>&1 || warn "could not pre-pull the image; 'up' will try again"
info "starting the stack ..."
# shellcheck disable=SC2086
$COMPOSE up -d

# --- wait for the app to answer ---------------------------------------------
http_ok() {
	if have curl; then
		curl -fsS -o /dev/null "http://localhost:${PORT}/healthz" 2>/dev/null
	elif have wget; then
		wget -q -O /dev/null "http://localhost:${PORT}/healthz" 2>/dev/null
	else
		return 2
	fi
}

info "waiting for SlateDesk to become healthy ..."
i=0
ready=0
while [ "$i" -lt 60 ]; do
	# Capture http_ok's status directly (0 healthy, 2 = no http client). A
	# bare `if http_ok; then` would swallow the 2 — the compound exits 0 when
	# the condition is false with no else — so the "no client" branch never
	# fires. `|| rc=$?` keeps set -e happy on the non-zero paths.
	rc=0
	http_ok || rc=$?
	if [ "$rc" -eq 0 ]; then
		ready=1
		break
	fi
	if [ "$rc" -eq 2 ]; then
		warn "neither curl nor wget found — skipping the health check"
		break
	fi
	i=$((i + 1))
	sleep 2
done

echo
if [ "$ready" = 1 ]; then
	info "SlateDesk is up at http://localhost:${PORT}/"
else
	warn "could not confirm health automatically; check '$COMPOSE logs app'"
fi

# --- point the operator at the one-time setup URL ---------------------------
# The app always logs the setup URL with its container-internal port (:8000),
# but the operator reaches it on the host at $PORT. Pull the signed token out
# of the logs and rebuild the URL against $PORT so a non-default SLATEDESK_PORT
# still hands the operator a URL that actually opens.
# shellcheck disable=SC2086
setup_token=$($COMPOSE logs app 2>&1 | sed -n 's|.*/setup?token=\([^ "]*\).*|\1|p' | tail -n1)

if [ -n "$setup_token" ]; then
	cat <<EOF

  Next step — open the first-run setup wizard in your browser:

      http://localhost:${PORT}/setup?token=${setup_token}

  This one-time URL (a signed token — never a default password) creates the
  admin account. Manage the stack with '$COMPOSE ps', '$COMPOSE logs -f app',
  '$COMPOSE down'. Back up with the bare binary or the recipe in docs/deploy.md.
EOF
else
	cat <<EOF

  Next step — open the first-run setup wizard.
  SlateDesk prints a one-time setup URL (with a signed token) to its logs on
  first boot. Never a default password. Find the token with:

      cd $(pwd)
      $COMPOSE logs app | grep -i setup

  The logged URL shows the container-internal port (:8000); on the host, open
  it as http://localhost:${PORT}/setup?token=... instead. Manage the stack with
  '$COMPOSE ps', '$COMPOSE logs -f app', '$COMPOSE down'. Back up with the bare
  binary or the recipe in docs/deploy.md.
EOF
fi
