// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Role.
const (
	Admin    Role = "admin"
	Agent    Role = "agent"
	Customer Role = "customer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Agent:
		return true
	case Customer:
		return true
	default:
		return false
	}
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	// Description Defaults to '' when omitted.
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// Company Defaults to '' when omitted.
	Company *string             `json:"company,omitempty"`
	Email   openapi_types.Email `json:"email"`
	Name    string              `json:"name"`

	// Password Optional initial password (minimum 10 characters). Omit for users
	// who will authenticate via OIDC (M5) or never log in.
	Password *string `json:"password,omitempty"`

	// Role User role.
	Role Role `json:"role"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Problem RFC 9457 problem details. Media type application/problem+json.
type Problem struct {
	// Detail Occurrence-specific explanation.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying this occurrence (request path).
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code.
	Status int `json:"status"`

	// Title Short human-readable summary of the problem type.
	Title string `json:"title"`

	// Type Problem type URI; "about:blank" when unspecified.
	Type *string `json:"type,omitempty"`
}

// Role User role.
type Role string

// SetTeamMembersRequest defines model for SetTeamMembersRequest.
type SetTeamMembersRequest struct {
	// UserIds Complete replacement membership list. May be empty.
	UserIds []openapi_types.UUID `json:"user_ids"`
}

// Team A team (routing queue).
type Team struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// TeamWithMembers A team including its member users.
type TeamWithMembers struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Members     []User             `json:"members"`
	Name        string             `json:"name"`
}

// UpdateTeamRequest Partial update; omitted fields are left unchanged.
type UpdateTeamRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateUserRequest Partial update; omitted fields are left unchanged.
type UpdateUserRequest struct {
	Active  *bool   `json:"active,omitempty"`
	Company *string `json:"company,omitempty"`
	Name    *string `json:"name,omitempty"`

	// Password New password (minimum 10 characters); bumps token_version
	// (logout everywhere).
	Password *string `json:"password,omitempty"`

	// Role User role.
	Role *Role `json:"role,omitempty"`
}

// User A SlateDesk user. Sensitive columns (password_hash, oidc_subject,
// token_version) are never serialized.
type User struct {
	// Active Deactivated users cannot log in; false means soft-deleted.
	Active bool `json:"active"`

	// Company Free-form company label ('' when unset).
	Company   string              `json:"company"`
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`

	// Role User role.
	Role Role `json:"role"`
}

// TeamID defines model for TeamID.
type TeamID = openapi_types.UUID

// UserID defines model for UserID.
type UserID = openapi_types.UUID

// BadRequest RFC 9457 problem details. Media type application/problem+json.
type BadRequest = Problem

// Forbidden RFC 9457 problem details. Media type application/problem+json.
type Forbidden = Problem

// NotFound RFC 9457 problem details. Media type application/problem+json.
type NotFound = Problem

// Unauthorized RFC 9457 problem details. Media type application/problem+json.
type Unauthorized = Problem

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Role Filter by role.
	Role *Role `form:"role,omitempty" json:"role,omitempty"`

	// Active Filter by active flag.
	Active *bool `form:"active,omitempty" json:"active,omitempty"`

	// Q Case-insensitive substring match against email and name.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Limit Page size.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Page offset.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = CreateTeamRequest

// UpdateTeamJSONRequestBody defines body for UpdateTeam for application/json ContentType.
type UpdateTeamJSONRequestBody = UpdateTeamRequest

// SetTeamMembersJSONRequestBody defines body for SetTeamMembers for application/json ContentType.
type SetTeamMembersJSONRequestBody = SetTeamMembersRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Log in with email and password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Log out
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetCurrentUser Get the authenticated user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// ListTeams List teams
	// (GET /teams)
	ListTeams(w http.ResponseWriter, r *http.Request)
	// CreateTeam Create a team
	// (POST /teams)
	CreateTeam(w http.ResponseWriter, r *http.Request)
	// DeleteTeam Delete a team
	// (DELETE /teams/{id})
	DeleteTeam(w http.ResponseWriter, r *http.Request, id TeamID)
	// GetTeam Get a team with its members
	// (GET /teams/{id})
	GetTeam(w http.ResponseWriter, r *http.Request, id TeamID)
	// UpdateTeam Update a team
	// (PATCH /teams/{id})
	UpdateTeam(w http.ResponseWriter, r *http.Request, id TeamID)
	// SetTeamMembers Replace team membership
	// (PUT /teams/{id}/members)
	SetTeamMembers(w http.ResponseWriter, r *http.Request, id TeamID)
	// ListUsers List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// CreateUser Create a user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// DeactivateUser Deactivate a user
	// (DELETE /users/{id})
	DeactivateUser(w http.ResponseWriter, r *http.Request, id UserID)
	// GetUser Get a user
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id UserID)
	// UpdateUser Update a user
	// (PATCH /users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id UserID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login Log in with email and password
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Log out
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrentUser Get the authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListTeams List teams
// (GET /teams)
func (_ Unimplemented) ListTeams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateTeam Create a team
// (POST /teams)
func (_ Unimplemented) CreateTeam(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteTeam Delete a team
// (DELETE /teams/{id})
func (_ Unimplemented) DeleteTeam(w http.ResponseWriter, r *http.Request, id TeamID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetTeam Get a team with its members
// (GET /teams/{id})
func (_ Unimplemented) GetTeam(w http.ResponseWriter, r *http.Request, id TeamID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateTeam Update a team
// (PATCH /teams/{id})
func (_ Unimplemented) UpdateTeam(w http.ResponseWriter, r *http.Request, id TeamID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SetTeamMembers Replace team membership
// (PUT /teams/{id}/members)
func (_ Unimplemented) SetTeamMembers(w http.ResponseWriter, r *http.Request, id TeamID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListUsers List users
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateUser Create a user
// (POST /users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeactivateUser Deactivate a user
// (DELETE /users/{id})
func (_ Unimplemented) DeactivateUser(w http.ResponseWriter, r *http.Request, id UserID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUser Get a user
// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id UserID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateUser Update a user
// (PATCH /users/{id})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, id UserID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTeams operation middleware
func (siw *ServerInterfaceWrapper) ListTeams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTeams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTeam operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeam(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeam(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeam operation middleware
func (siw *ServerInterfaceWrapper) GetTeam(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeam(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTeam operation middleware
func (siw *ServerInterfaceWrapper) UpdateTeam(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTeam(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetTeamMembers operation middleware
func (siw *ServerInterfaceWrapper) SetTeamMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetTeamMembers(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "role" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "role", r.URL.Query(), &params.Role, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "role"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "role", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "active", r.URL.Query(), &params.Active, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "active"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeactivateUser operation middleware
func (siw *ServerInterfaceWrapper) DeactivateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeactivateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}", wrapper.DeactivateUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{id}", wrapper.UpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/teams", wrapper.ListTeams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/teams", wrapper.CreateTeam)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/teams/{id}", wrapper.DeleteTeam)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/teams/{id}", wrapper.GetTeam)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/teams/{id}", wrapper.UpdateTeam)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/teams/{id}/members", wrapper.SetTeamMembers)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FvdTxtJEv9XSnMnLegG22SJTjHaB5Yku+hCQEDuHmIU2jNlT296uifdPTjeiP/9VN3zac+AWT52Fe0b",
	"tmeqquu7ftV8CyKVZkqitCYYfwsyplmKFrX7dIEsPXpNf8VoIs0zy5UMxu574PEgCANOnzNmkyAMJEsx",
	"GAc8DsJA45eca4yDsdU5hoGJEkwZkZopnTIbjIM8d0/aZUZvGau5nAc3N2HwwaDuYkvfPxnbG3rZZEoa",
	"dGf/mcVn+CVHY+lTpKRF6f5kWSZ4xEimYabVVGD6r98MCfitwe6fGmfBOPjHsNbv0P9qhqf+Lc+0fcRj",
	"JkhQjEF75jBV8RKUhtoyg+AmDN4qPeVxjPI5pTvIbYLSEn2MYZpbkMoCE0ItMAarIENN4oNNuAEW0WtO",
	"2vfKvlW5jJ9T2PcKTB4loNGoXEfoBCmff06lySUom6AG1FrpEJiBs7eH8Grv5b+h4AYxWsaFN+0HyXKb",
	"KM1/x2dV2DE3hst5CFxeM8HjkNwOv2YUT2DQGG/NmzKqXJgcamQWKSE0oiXTKkNtuY+kFpfVmH6NM5YL",
	"a8h7fvgBFglKUCm3Fl2cr0RpGezfgpTLdyjnNgnGu105pE4EH/07l9VTavobRpaIeeEprfQKTypkcvlw",
	"wTFlXLQSkf/mljOu/ZAxYxZKx+vSnLg/mAAuueVMQPkobKVc8jRPYXcEUcI0iyiHbA/gJOUWZkpDblCb",
	"iVwkChZcCGCNKIdrzuDk6PUhbB2/3CaHkHiNGoSaA5eDiQzClilGHcfRSuBdbnlGz6zarVSQ00dBp8uM",
	"79Scy14L3kPxTf3ex8FKgtX7XVI2Uk/bdr3JAI4x5gyIEvRFPvnaarjZ4sArLhJFudYoI9wxGUZ8xiOK",
	"bsEk83m6QyFcGstkhB21+OwINM7QEQQek8PMllzOfe5XFTPYKisZlettYlOXYs13KiJd/I1lNl9PIsGv",
	"Fxen4H+ESMVIVFP2lfw8GL989co5pf+0O6p9kkuLc9RE2XIrOo51nihtIclTJnc0sphNBYLJ05TpJagZ",
	"2AQrMxHRTq35L4i0SxHBOGBTldvxVDD5OVhNu6cNcvDh7GgfJs3nJ4HPLbksrObzy6Y6XPFUf+xKsV1+",
	"eqa6FON6L4pAYo6SNPsxiHJjVYo6CAM2pxIVBixOuWzQrbVyjpbKxDGmU9SmN1wpG33icYfRD1WaCbQI",
	"GjPBIkxRWkg9uYRnILixAzhmS5giYJrZpesULaZmgwaw+oJpzZZriqvE6lIZnWtd3gOw1CdvaZVbCowv",
	"Oea43RWwrfq4HoTxRuL3VI2Vc7h3i4TaZNx3rP9xmxQmcw2IECezYPzx9mzu9HETrpo2relUVrmNDPnc",
	"nYYpia4f4DLsNgiXkchjsgi3pnAgXwR9+5XF6x3NSsgy7Yps7h7dL+s+zDiK2ADTCAJnFnIZJUzOfcTe",
	"z+ib9jlrRvPir/Q0jy4+9fbXTXebKiWQSZKg0TI9RmvzHhd3djP7MM3TjHqxzyg/XaOmXnUit4Saq9wC",
	"tSzLRYIat5+gZVk3AfltRzo4F8ziazSfnbcN4Byl4aRHiJTIU2lgqzzop4SZJATF4+iTyR3lcCJbx9t2",
	"hvLtmEHNmaCBwZ+vz1irLaz7xQ1zzv8hYpImOt/d7cOMCYOQIpMGjJrZnRgpATcb3G67t/m81Yg7bi4s",
	"HgHBpihgq+ybc2nQbnfW0si16PEnZltJkBx3x/IUH9hqPyy3PqC3dXy6Gtxaj2FpuJYW1vMc9UkY5Zrb",
	"5TmxLAcX9ZkjTewdXQ6fS4zhV2uzEymW5XAH/h3YOmcpnnOLP71jX7chYloXnR06PwEeTySTcTvcBnAy",
	"tYwTYRoaTk/OL2BIs8RQUH++D5FApv2vE9n+WeXWO67DdbwYNbJj4k+FhLVtWMb/g0s/xnI5Ux2HrKLt",
	"+gW4hvHg9GgAx1ygsUoi7ILJ9YxFOAahItYafHz6MLfqaTv0UROC0wWy1AwmciIPhPCjvk+lfe09bF31",
	"NfVXRZoSPEJpnIMVqjjIWJTgzovBKAiDXItgHCTWZmY8HC4WiwFzPw+Ung+Ld83w3dHhm/fnb+idQWJT",
	"0eh+Gzo6OD0KwqAwZTAORoPdwYgeVRlKlvFgHPzovgod7OZcrGFd18eprmLzX9TUtBrnPZFGNykwYUhp",
	"ISgJJo8iNCYEg9Y/dVUb/GoiK+1v4J2FwUo7Of8cTORFQk2jB/c8oMaN7xD3vVieMvfsS6jDmYDyqDPQ",
	"URyM/aRZwIxo7M8qXt6C0NwPmWlNsTftfGF1jqsA5YvRXkeRaSJ0VGFagW3QUpJNkMVFH3aOdufQh9sa",
	"raYZ4PZQIKr1Kdeg1Zsw2BuN+hRQnWrYwFzdK7vPCX8dedSr5aNKQ9wokiyKVC6taxP3Xrx6TukulILU",
	"lU5yE2DWkv+afdBoNRVUi9rJVQ2ddym7ZlbXj2D88TIMinnX+ztwCQtuE3DFyqW6qlcLA8vmhsoZZYLg",
	"kkg1c3p/VjikWtAKt9KT4EAs2NL4tICxcRAVawHPTMYTmcv2lxETgloYJvhn3AceY5opMk1PHJN4m0TU",
	"SggVReweYfSmQFBb4bRp2Dy6Nf2x+8zmu5w5OoZtlf2C9tBBOta1t2uqGz1aIvRjX0cIlO3HutfAFIWS",
	"cxoABo3UcbvKWjj7H9Z1pd1f0DrJ2m6Ze2V1KNw1DL3qfseNg0vMQzW90aRdDOyrk/b6LkMI3+iEYJR2",
	"S6AlUGvyx7W+N/rx7pfqbdfD7USa9Ydo2MV/vqRBtMhXbXPUa44nqv7re5SNWoDdRxPAu0BH1CFLoZg/",
	"Civ/0Ur+1I6xN3rWklzASa44OtCbAgGY0MjiJeBXbqwZPILDetcA5th1+GyVTIbfeHzjCxCN6R2wOdMx",
	"+B8HcFwjp1otaPY3EYtxv4ACaHTJpVV5lPhy1w6I145KFRB3VVHnRRV68JwusXf3G9V2+uG28mrpt1XY",
	"W1y7VTl61Phugrk9BZYEDRsQ6Ro8+p0ajqo3awR0DQ33lInGRZkeNLx+ZFhcpLm5dNNzlDwSJtt2ohq4",
	"fqIatY6Mb1SjRk9fo6gzdMJ5HOYvX6fu6dvfaWHz/rRpYRs21kdZ3jFTnvm1oJ8qZ7kQq8tBf6KrcpV3",
	"BVv1lAinHy62BxP5QX6WaiFLnNPAjKZeorhIlMDqWpYjtTca7YNUNnHLJOOX9BhPZOajWSy7hs/2IjR4",
	"QC55iiDvXtP+CYG+YbGq07XERcPi31sOeGCsFcHhVVZrqSfqXLm/dTb9YDp9d2Xxw4VFTTNieXPA4ftf",
	"ctTLGt4v1h6beUa5TOln5ZcmMBNs3sex2qusgS/VOmudwyEzuMOlqZZ2Jp96rAZSqunA5oxLYxtAmZ+M",
	"u2X4civ2E673B3MEw3/vpSd4ym2LZuUxL0eN2zEvRqPm7Zj1uzE9vNVsVsDHXdz9r93sm/w67uL4RPbU",
	"CEfPXYKOC7g2cum8WO1IXFC6n3Ft7F88pTwGLpKbdsPrP9+Fi1SI4FPhIs3rDM+Mi/Shke5C1N+4SGf7",
	"6Jqnun0sEuLTASMrIGvptFUluxMYOVczW8ATY7+HvPI14id3BeLKZXN/xeSqtfS+AqOACTGRKrfGMumG",
	"5gKcNhBzHIDbPqoFNYga/YbcrR212zhKBQnT8UR69sAlHO92tY31bY1uAH6v59JeY4H1fSMv5TH7HaIf",
	"ffmzdxrfP7TSa5L7TT/F/wY9KpIC52jdDc2rcrN5NZEaE2aSYpqs7p/15oHqvyaYo+RunHUmBbfPLG/S",
	"DOCNy43cAE/T3Lrrxr0ZoL7a96QAz72L7TOFSQHwNMLl7+FuBUjpK4TtpXD7ctjHSwomg/q6e4g7Zynu",
	"KM3nXMLB6RGk/gpEef1oyDI+vN51EVnw7VuhCz7DaBkJdDEw1WrheijB6ZCDxnhGcq2PIa6apUyyubv6",
	"PYCDOOUSlBTLEPBrhJkFajEo2JYq1wbFzF1FK3fbDRZeM+s83Mp15cq22fYXvBLkugUwVNT86HxzefP/",
	"AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
