/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Verifies the credentials and, on success, sets the `sd_session`
         *     HttpOnly cookie (SameSite=Lax) carrying the signed session token.
         *     The response body is empty; the cookie is the session.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Clears the session cookie. Always succeeds for authenticated and
         *     unauthenticated callers alike; idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create a user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        /** Get a user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /**
         * Deactivate a user
         * @description Soft delete: sets `active=false` and bumps `token_version` so all
         *     outstanding sessions die. The row is retained; there is no hard
         *     delete in M1.
         */
        delete: operations["deactivateUser"];
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Partial update; omitted fields are left unchanged. Setting `password`
         *     rehashes the password and bumps `token_version`, invalidating every
         *     outstanding session for the user. Email is immutable in M1.
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams */
        get: operations["listTeams"];
        put?: never;
        /** Create a team */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        /** Get a team with its members */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        /**
         * Delete a team
         * @description Hard delete. Membership rows cascade; users are untouched.
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        /**
         * Update a team
         * @description Partial update; omitted fields are left unchanged.
         */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace team membership
         * @description Replaces the full membership list with `user_ids` (idempotent PUT).
         *     Unknown user ids fail the whole request with 400; nothing is applied
         *     partially.
         */
        put: operations["setTeamMembers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description User role.
         * @enum {string}
         */
        Role: "customer" | "agent" | "admin";
        /**
         * @description A SlateDesk user. Sensitive columns (password_hash, oidc_subject,
         *     token_version) are never serialized.
         */
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /** @description Free-form company label ('' when unset). */
            company: string;
            /** @description Deactivated users cannot log in; false means soft-deleted. */
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @description A team (routing queue). */
        Team: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
        };
        /** @description A team including its member users. */
        TeamWithMembers: components["schemas"]["Team"] & {
            members: components["schemas"]["User"][];
        };
        /** @description RFC 9457 problem details. Media type application/problem+json. */
        Problem: {
            /**
             * Format: uri-reference
             * @description Problem type URI; "about:blank" when unspecified.
             * @default about:blank
             */
            type: string;
            /** @description Short human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Occurrence-specific explanation. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying this occurrence (request path).
             */
            instance?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /**
             * @description Optional initial password (minimum 10 characters). Omit for users
             *     who will authenticate via OIDC (M5) or never log in.
             */
            password?: string;
            /** @description Defaults to '' when omitted. */
            company?: string;
        };
        /** @description Partial update; omitted fields are left unchanged. */
        UpdateUserRequest: {
            name?: string;
            role?: components["schemas"]["Role"];
            company?: string;
            active?: boolean;
            /**
             * @description New password (minimum 10 characters); bumps token_version
             *     (logout everywhere).
             */
            password?: string;
        };
        CreateTeamRequest: {
            name: string;
            /** @description Defaults to '' when omitted. */
            description?: string;
        };
        /** @description Partial update; omitted fields are left unchanged. */
        UpdateTeamRequest: {
            name?: string;
            description?: string;
        };
        SetTeamMembersRequest: {
            /** @description Complete replacement membership list. May be empty. */
            user_ids: string[];
        };
    };
    responses: {
        /** @description Malformed request body or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, invalid, or expired session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated but not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Any other error, as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description User id. */
        UserID: string;
        /** @description Team id. */
        TeamID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. Session cookie set. */
            204: {
                headers: {
                    /** @description `sd_session` signed HttpOnly session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid credentials or deactivated account. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Too many login attempts; retry later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared. */
            204: {
                headers: {
                    /** @description Expired `sd_session` cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user the session cookie belongs to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Problem"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Filter by role. */
                role?: components["schemas"]["Role"];
                /** @description Filter by active flag. */
                active?: boolean;
                /** @description Case-insensitive substring match against email and name. */
                q?: string;
                /** @description Page size. */
                limit?: number;
                /** @description Page offset. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching users, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A user with this email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    deactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All teams, sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Team created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A team with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The team, including member users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamWithMembers"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            /** @description The updated team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A team with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTeamMembersRequest"];
            };
        };
        responses: {
            /** @description The team with its new membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamWithMembers"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
}
