/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Verifies the credentials and, on success, sets the `sd_session`
         *     HttpOnly cookie (SameSite=Lax) carrying the signed session token.
         *     The response body is empty; the cookie is the session.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Clears the session cookie. Always succeeds for authenticated and
         *     unauthenticated callers alike; idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create a user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        /** Get a user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /**
         * Deactivate a user
         * @description Soft delete: sets `active=false` and bumps `token_version` so all
         *     outstanding sessions die. The row is retained; there is no hard
         *     delete in M1.
         */
        delete: operations["deactivateUser"];
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Partial update; omitted fields are left unchanged. Setting `password`
         *     rehashes the password and bumps `token_version`, invalidating every
         *     outstanding session for the user. Email is immutable in M1.
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams */
        get: operations["listTeams"];
        put?: never;
        /** Create a team */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        /** Get a team with its members */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        /**
         * Delete a team
         * @description Hard delete. Membership rows cascade; users are untouched.
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        /**
         * Update a team
         * @description Partial update; omitted fields are left unchanged.
         */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/teams/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace team membership
         * @description Replaces the full membership list with `user_ids` (idempotent PUT).
         *     Unknown user ids fail the whole request with 400; nothing is applied
         *     partially.
         */
        put: operations["setTeamMembers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tickets
         * @description Filtered, paginated ticket list, most recent activity first
         *     (`updated_at` descending), or by relevance when `q` is present.
         *     Requires agent or admin role.
         *
         *     `view` applies one of the fixed workspace views; every other
         *     filter composes with it (logical AND):
         *
         *       - `my` — assigned to the caller, not closed
         *       - `unassigned` — no assignee, not closed
         *       - `open` — status is open, waiting_on_customer, or on_hold
         *       - `closed` — status is closed
         */
        get: operations["listTickets"];
        put?: never;
        /**
         * Create a ticket
         * @description Creates a ticket and its first article in one transaction: the
         *     day's ticket number (YYYYMMDD-NNNN) is allocated atomically, the
         *     body is recorded as an agent-authored public article
         *     (`sender_type=agent`, `channel=web`), and a `created` audit event
         *     plus a `ticket.created` stream event are emitted. The ticket
         *     starts `open`; priority defaults to `medium`. Requires agent or
         *     admin role.
         */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket id. */
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        /**
         * Get a ticket with its full thread
         * @description The ticket plus requester/assignee summaries, tags, every article
         *     in chronological order (each carrying its attachments), and the
         *     audit event trail. Requires agent or admin role.
         */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update ticket fields
         * @description Partial update of status, priority, assignee, and team. Omitted
         *     fields are left unchanged; an explicit `null` for `assignee_id`
         *     or `team_id` clears that field. Setting `status=open` on a closed
         *     ticket is the reopen path. Every change is audited and emits a
         *     `ticket.updated` stream event. Requires agent or admin role.
         */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/tickets/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a ticket's tags
         * @description Replaces the full tag set with `tag_ids` (idempotent PUT). Unknown
         *     tag ids fail the whole request with 400; nothing is applied
         *     partially. Emits a `tags_changed` audit event and a
         *     `ticket.updated` stream event. Requires agent or admin role.
         */
        put: operations["setTicketTags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add an article to a ticket
         * @description Appends an agent-authored article (`sender_type=agent`,
         *     `channel=web`) — a public reply or, with `is_internal=true`, an
         *     internal note. `body_html`, when provided, is sanitized
         *     server-side (bluemonday) before storage. A public reply on an
         *     open ticket flips it to `waiting_on_customer`; internal notes
         *     never change status. Emits an `article_added` audit event and an
         *     `article.created` stream event. Requires agent or admin role.
         */
        post: operations["createTicketArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an attachment to an article
         * @description Multipart upload of one file (part name `file`), streamed to blob
         *     storage — the whole request body is capped at 25 MiB. The stored
         *     filename is the part's filename, sanitized; the content type is
         *     taken from the part header (falling back to
         *     `application/octet-stream`). Requires agent or admin role.
         */
        post: operations["uploadArticleAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}/retry-send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a failed outbound email delivery
         * @description Re-enqueues the email delivery of an outbound article whose
         *     `delivery_status` is `failed` (the terminal badge after the send
         *     job exhausted its retries). The article flips back to `queued`
         *     (emitting an `article.updated` stream event) and the send is
         *     retried with the **same** Message-ID that was committed before
         *     the first attempt, so a duplicate delivery can never fork the
         *     email thread. Only `failed` articles can be retried — anything
         *     else answers 409, with one recovery exception: an article stuck
         *     on `sending` whose send job no longer exists (the worker crashed
         *     on its final attempt) is also accepted; a send genuinely in
         *     flight still answers 409. Requires agent or admin role.
         */
        post: operations["retryArticleSend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download an attachment
         * @description Streams the attachment bytes. The response `Content-Type` is the
         *     attachment's stored content type (`application/octet-stream`
         *     below is the declared fallback), and `Content-Disposition` is
         *     always `attachment` with a sanitized filename — attachments are
         *     downloads, never inline renders. Requires agent or admin role.
         */
        get: operations["downloadAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tags
         * @description All tags, sorted by name. Requires agent or admin role.
         */
        get: operations["listTags"];
        put?: never;
        /**
         * Create a tag
         * @description Tag names are case-insensitively unique. Requires agent or admin
         *     role.
         */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag id. */
                id: components["parameters"]["TagID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a tag
         * @description Hard delete; the tag disappears from every ticket (ticket_tags
         *     rows cascade). **Admin only.**
         */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        /**
         * Update a tag
         * @description Partial update; omitted fields are left unchanged; explicit
         *     `color: null` clears the color. Requires agent or admin role.
         */
        patch: operations["updateTag"];
        trace?: never;
    };
    "/dashboard/counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the dashboard counters
         * @description The four workspace counters in one call. `closed_today` counts
         *     tickets closed since midnight in the database's timezone (UTC in
         *     deployment). Requires agent or admin role.
         */
        get: operations["getDashboardCounters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Realtime event stream (SSE)
         * @description Server-Sent Events stream of ticket activity, intended for
         *     workspace cache invalidation. Each event is one `data:` frame
         *     whose payload is a JSON `StreamEvent` (`{type, ticket_id}`); no
         *     SSE `event:` or `id:` fields are used. Event types:
         *     `ticket.created`, `ticket.updated`, `article.created`,
         *     `article.updated` (an existing article changed — in M3 that is
         *     an email `delivery_status` transition), plus `resync` (no
         *     `ticket_id`) when the server may have dropped events (e.g. it
         *     re-established its own database LISTEN connection) — on
         *     `resync` a client must refetch everything it displays.
         *
         *     Events are invalidation hints, not a durable feed: a client that
         *     connects (or reconnects) must refetch whatever it displays. A
         *     comment heartbeat (`: ping`) is written every ~25 seconds to keep
         *     intermediaries from closing idle connections. Requires agent or
         *     admin role.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List mailboxes
         * @description All configured mailboxes with their connection config and health
         *     columns (`last_poll_at`, `last_error`, `last_error_at`) feeding
         *     the admin screen's health pills. Credentials are never included.
         *     **Admin only.**
         */
        get: operations["listMailboxes"];
        put?: never;
        /**
         * Create a mailbox
         * @description Creates a mailbox. The request is discriminated on `auth_kind`;
         *     each kind carries its own write-only credential fields:
         *
         *       - `basic` — `password` (IMAP/SMTP login password)
         *       - `oauth_m365` — `tenant_id`, `client_id`, `client_secret`
         *         (Entra app registration; client-credentials XOAUTH2)
         *       - `oauth_google` — `client_id`, `client_secret` (Google Cloud
         *         OAuth client; the offline refresh token is obtained
         *         afterwards via `POST /mailboxes/{id}/oauth/google/start`)
         *
         *     Secrets are encrypted at rest and **never** returned by any
         *     response. New mailboxes default to `active=true`; the poller
         *     adopts an active mailbox within one lease interval. **Admin
         *     only.**
         */
        post: operations["createMailbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mailbox id. */
                id: components["parameters"]["MailboxID"];
            };
            cookie?: never;
        };
        /**
         * Get a mailbox
         * @description Connection config and health; never credentials. **Admin only.**
         */
        get: operations["getMailbox"];
        put?: never;
        post?: never;
        /**
         * Delete a mailbox
         * @description Hard delete: the poller drops the mailbox and its lease. Email
         *     threading state survives (recorded Message-IDs keep their
         *     tickets; only their mailbox link is cleared), so replies to mail
         *     sent through the deleted mailbox still thread correctly if
         *     another mailbox receives them. **Admin only.**
         */
        delete: operations["deleteMailbox"];
        options?: never;
        head?: never;
        /**
         * Update a mailbox
         * @description Partial update; omitted fields are left unchanged. The write-only
         *     credential fields rotate the stored secrets: `password` (basic),
         *     `tenant_id`/`client_id`/`client_secret` (OAuth kinds). Rotating a
         *     credential drops any cached OAuth access token; rotating an
         *     `oauth_google` client additionally invalidates the stored refresh
         *     token, so the Google connect flow must be run again. Changing
         *     `auth_kind` requires supplying the credential fields the new kind
         *     needs (400 otherwise). The response never echoes secrets. **Admin
         *     only.**
         */
        patch: operations["updateMailbox"];
        trace?: never;
    };
    "/mailboxes/{id}/test-fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test the mailbox's IMAP connection
         * @description Performs a live IMAP dial + authentication + SELECT INBOX with
         *     the stored credentials and reports the outcome. A failed test is
         *     a **200 with `ok=false`** — the test ran; its result is the
         *     payload. Non-2xx responses mean the test could not be attempted
         *     at all. May take several seconds (network timeouts). **Admin
         *     only.**
         */
        post: operations["testMailboxFetch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes/{id}/test-send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a test email through the mailbox
         * @description Performs a live SMTP dial + authentication and sends a short
         *     test message to `to` from the mailbox's address. A failed send
         *     is a **200 with `ok=false`**; non-2xx means the test could not
         *     be attempted. The test mail carries auto-generated headers
         *     (`Auto-Submitted`, `X-Auto-Response-Suppress`) so it can never
         *     start an autoresponder loop, and it is not recorded on any
         *     ticket. **Admin only.**
         */
        post: operations["testMailboxSend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes/{id}/oauth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the Google OAuth connect flow
         * @description Builds the Google authorization URL for an `oauth_google`
         *     mailbox (authorization-code flow with offline access, so the
         *     exchange yields a refresh token) and returns it for the browser
         *     to navigate to. The `redirect_uri` is derived from the instance
         *     external URL setting
         *     (`{external_url}/api/v1/mailboxes/oauth/google/callback`) and
         *     must be registered on the Google OAuth client. The signed,
         *     single-use `state` parameter binds the callback to this mailbox
         *     and session. 409 when the mailbox is not `oauth_google` or the
         *     external URL setting is unset. **Admin only.**
         */
        post: operations["startMailboxGoogleOauth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailboxes/oauth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth redirect target
         * @description Browser redirect target of the Google connect flow — not called
         *     by API clients. Validates `state` (signed, single-use, bound to
         *     the mailbox and the initiating admin session), exchanges `code`
         *     for tokens, persists the refresh token into the mailbox's
         *     encrypted credentials, and redirects to
         *     `/settings/mailboxes?connected=1`. Because this is a top-level
         *     navigation, the admin's SameSite=Lax session cookie is sent —
         *     the endpoint is as **admin only** as the rest of the mailbox
         *     surface. A missing/invalid `state`, a provider `error`, or a
         *     failed code exchange is a 400 problem; nothing is persisted.
         */
        get: operations["mailboxGoogleOauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/external-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the instance external URL
         * @description The public base URL this instance is reached at (used to build
         *     the Google OAuth `redirect_uri`; later, links in outbound
         *     email). `external_url` is `""` until configured. **Admin only.**
         */
        get: operations["getExternalUrl"];
        /**
         * Set the instance external URL
         * @description Sets the public base URL: an absolute `http`/`https` URL with no
         *     path, query, or fragment (e.g. `https://desk.example.com`); a
         *     trailing slash is stripped. Idempotent PUT. **Admin only.**
         */
        put: operations["setExternalUrl"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description User role.
         * @enum {string}
         */
        Role: "customer" | "agent" | "admin";
        /**
         * @description A SlateDesk user. Sensitive columns (password_hash, oidc_subject,
         *     token_version) are never serialized.
         */
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /** @description Free-form company label ('' when unset). */
            company: string;
            /** @description Deactivated users cannot log in; false means soft-deleted. */
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @description A team (routing queue). */
        Team: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
        };
        /** @description A team including its member users. */
        TeamWithMembers: components["schemas"]["Team"] & {
            members: components["schemas"]["User"][];
        };
        /** @description RFC 9457 problem details. Media type application/problem+json. */
        Problem: {
            /**
             * Format: uri-reference
             * @description Problem type URI; "about:blank" when unspecified.
             * @default about:blank
             */
            type: string;
            /** @description Short human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Occurrence-specific explanation. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying this occurrence (request path).
             */
            instance?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /**
             * @description Optional initial password (minimum 10 characters). Omit for users
             *     who will authenticate via OIDC (M5) or never log in.
             */
            password?: string;
            /** @description Defaults to '' when omitted. */
            company?: string;
        };
        /** @description Partial update; omitted fields are left unchanged. */
        UpdateUserRequest: {
            name?: string;
            role?: components["schemas"]["Role"];
            company?: string;
            active?: boolean;
            /**
             * @description New password (minimum 10 characters); bumps token_version
             *     (logout everywhere).
             */
            password?: string;
        };
        CreateTeamRequest: {
            name: string;
            /** @description Defaults to '' when omitted. */
            description?: string;
        };
        /** @description Partial update; omitted fields are left unchanged. */
        UpdateTeamRequest: {
            name?: string;
            description?: string;
        };
        SetTeamMembersRequest: {
            /** @description Complete replacement membership list. May be empty. */
            user_ids: string[];
        };
        /**
         * @description Ticket lifecycle status.
         * @enum {string}
         */
        TicketStatus: "open" | "waiting_on_customer" | "on_hold" | "closed";
        /**
         * @description Ticket priority.
         * @enum {string}
         */
        TicketPriority: "low" | "medium" | "high" | "critical";
        /**
         * @description Fixed workspace views: `my` (assigned to the caller, not closed),
         *     `unassigned` (no assignee, not closed), `open` (any non-closed
         *     status), `closed` (closed only).
         * @enum {string}
         */
        TicketView: "my" | "unassigned" | "open" | "closed";
        /**
         * @description Who authored an article.
         * @enum {string}
         */
        ArticleSenderType: "customer" | "agent" | "system";
        /**
         * @description The channel an article arrived through.
         * @enum {string}
         */
        ArticleChannel: "email" | "api" | "web";
        /** @description Compact user reference embedded in tickets and articles. */
        UserSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        /** @description A ticket, as returned by list and update operations. */
        Ticket: {
            /** Format: uuid */
            id: string;
            /** @description Human-facing ticket number (YYYYMMDD-NNNN). */
            number: string;
            subject: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            requester: components["schemas"]["UserSummary"];
            /** @description Assigned agent; null when unassigned. */
            assignee: components["schemas"]["UserSummary"] | null;
            /**
             * Format: uuid
             * @description Owning team; null when not routed to a team.
             */
            team_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description Set while the ticket is closed; null otherwise.
             */
            closed_at: string | null;
        };
        /** @description One page of tickets plus the pre-pagination match count. */
        TicketList: {
            items: components["schemas"]["Ticket"][];
            /**
             * Format: int64
             * @description Total matching tickets before limit/offset.
             */
            total: number;
        };
        /**
         * @description A ticket with its full thread: tags, every article in
         *     chronological order (each carrying its attachments), and the
         *     audit event trail.
         */
        TicketDetail: components["schemas"]["Ticket"] & {
            /** @description The ticket's tags, sorted by name. */
            tags: components["schemas"]["Tag"][];
            /** @description All articles, oldest first. */
            articles: components["schemas"]["Article"][];
            /** @description Audit trail, oldest first. */
            events: components["schemas"]["TicketEvent"][];
        };
        /**
         * @description One message in a ticket's thread. `body_html`, when present, was
         *     sanitized (bluemonday) at write time and is safe to render;
         *     `body_text` always exists and feeds search. `delivery_status` is
         *     the outbound email badge (null on articles that are not outbound
         *     email).
         */
        Article: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ticket_id: string;
            /** @description Authoring user; null for external or system authors. */
            author: components["schemas"]["UserSummary"] | null;
            sender_type: components["schemas"]["ArticleSenderType"];
            channel: components["schemas"]["ArticleChannel"];
            /** @description Internal notes are never shown to customers. */
            is_internal: boolean;
            body_text: string;
            /** @description Sanitized HTML body; null when the article is plain text. */
            body_html: string | null;
            /**
             * @description Outbound email delivery badge; null on articles that are not
             *     outbound email (inbound mail, internal notes, web/api
             *     articles on tickets without an email origin).
             */
            delivery_status: components["schemas"]["DeliveryStatus"] | null;
            /** @description Files attached to this article. */
            attachments: components["schemas"]["Attachment"][];
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Outbound email delivery state of an article. Transitions:
         *
         *       - `queued` — the article and its send job committed in one
         *         transaction; the job has not started yet.
         *       - `queued → sending` — the send worker committed the outbound
         *         Message-ID (threading is safe from here on) and is dialing
         *         SMTP. On worker crash the job retries from here with the
         *         same Message-ID.
         *       - `sending → sent` — the SMTP server accepted the message.
         *         Terminal.
         *       - `sending → failed` — every retry (capped backoff) failed.
         *         Terminal, shown as a visible badge; `POST
         *         /articles/{id}/retry-send` moves it back to `queued`.
         *       - `sending → queued` — recovery only: a worker crash on the
         *         final attempt can strand the badge on `sending` (the job is
         *         discarded without running); retry-send accepts that stuck
         *         state once no live send job remains.
         *
         *     Every transition emits an `article.updated` stream event.
         * @enum {string}
         */
        DeliveryStatus: "queued" | "sending" | "sent" | "failed";
        /** @description Attachment metadata; the bytes live at GET /attachments/{id}. */
        Attachment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            article_id: string;
            /** @description Sanitized original filename. */
            filename: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Slim audit event. `payload` is a small type-specific JSON
         *     document (e.g. `{"from": "open", "to": "closed"}` for
         *     status_changed).
         */
        TicketEvent: {
            /**
             * Format: int64
             * @description Insertion-ordered id (stable even within one transaction).
             */
            id: number;
            /** Format: uuid */
            ticket_id: string;
            /**
             * Format: uuid
             * @description Acting user; null for system actions.
             */
            actor_id: string | null;
            /**
             * @description Event type. One of: created, article_added, status_changed,
             *     priority_changed, assignee_changed, team_changed, tags_changed.
             */
            type: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        /** @description A tag. Names are case-insensitively unique. */
        Tag: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Display color hint (e.g. "#RRGGBB"); null when unset. */
            color: string | null;
        };
        /** @description The four workspace dashboard counters. */
        DashboardCounters: {
            /**
             * Format: int64
             * @description Tickets with status open.
             */
            open: number;
            /**
             * Format: int64
             * @description Non-closed tickets with no assignee.
             */
            unassigned: number;
            /**
             * Format: int64
             * @description Tickets with status waiting_on_customer.
             */
            waiting_on_customer: number;
            /**
             * Format: int64
             * @description Tickets closed since midnight (database timezone).
             */
            closed_today: number;
        };
        /**
         * @description JSON payload of one SSE `data:` frame on GET /events. A
         *     cache-invalidation hint, not a durable feed. `ticket_id` is
         *     present on the ticket-scoped types and absent on `resync`
         *     (which means: events may have been dropped, refetch everything).
         */
        StreamEvent: {
            /** @enum {string} */
            type: "ticket.created" | "ticket.updated" | "article.created" | "article.updated" | "resync";
            /** Format: uuid */
            ticket_id?: string;
        };
        CreateTicketRequest: {
            subject: string;
            /**
             * @description Plain-text body of the ticket's first article (recorded as an
             *     agent-authored public web article).
             */
            body: string;
            priority?: components["schemas"]["TicketPriority"];
            /**
             * Format: uuid
             * @description Route the ticket to this team.
             */
            team_id?: string;
            /**
             * Format: uuid
             * @description The user the ticket is for (e.g. opening a ticket on a
             *     customer's behalf). Defaults to the caller when omitted.
             */
            requester_id?: string;
        };
        /**
         * @description Partial update; omitted fields are left unchanged. `assignee_id`
         *     and `team_id` are tri-state: omitted = unchanged, a uuid = set,
         *     explicit null = cleared.
         */
        UpdateTicketRequest: {
            status?: components["schemas"]["TicketStatus"];
            priority?: components["schemas"]["TicketPriority"];
            /** Format: uuid */
            assignee_id?: string | null;
            /** Format: uuid */
            team_id?: string | null;
        };
        SetTicketTagsRequest: {
            /** @description Complete replacement tag set. May be empty. */
            tag_ids: string[];
        };
        CreateArticleRequest: {
            body_text: string;
            /**
             * @description Optional HTML rendering of the body; sanitized server-side
             *     (bluemonday UGC policy) before storage.
             */
            body_html?: string;
            /**
             * @description true = internal note (never customer-visible, never changes
             *     status); false = public reply.
             */
            is_internal: boolean;
        };
        CreateTagRequest: {
            name: string;
            /** @description Display color hint (e.g. "#RRGGBB"). */
            color?: string;
        };
        /**
         * @description Partial update; omitted fields are left unchanged; explicit
         *     `color: null` clears the color.
         */
        UpdateTagRequest: {
            name?: string;
            color?: string | null;
        };
        /**
         * @description How the mailbox authenticates to its IMAP/SMTP servers: `basic`
         *     (username + password), `oauth_m365` (Entra client-credentials
         *     XOAUTH2), `oauth_google` (Google authorization-code XOAUTH2 with
         *     an offline refresh token).
         * @enum {string}
         */
        MailboxAuthKind: "basic" | "oauth_m365" | "oauth_google";
        /**
         * @description TLS posture of a mail connection: `tls` (implicit TLS),
         *     `starttls` (mandatory STARTTLS upgrade), `none` (cleartext —
         *     local dev/test servers only; never use in production).
         * @enum {string}
         */
        MailTLSMode: "tls" | "starttls" | "none";
        /**
         * @description A configured email mailbox: connection config plus the health
         *     columns behind the admin screen's health pills. Credentials
         *     (password, client secret, OAuth tokens) are **never** included
         *     in any response.
         */
        Mailbox: {
            /** Format: uuid */
            id: string;
            /** @description Display name of the mailbox (e.g. "Support"). */
            name: string;
            /**
             * Format: email
             * @description The address this mailbox sends and receives as. Unique.
             */
            email_address: string;
            /** @description Inactive mailboxes are neither polled nor sent through. */
            active: boolean;
            auth_kind: components["schemas"]["MailboxAuthKind"];
            imap_host: string;
            imap_port: number;
            imap_tls_mode: components["schemas"]["MailTLSMode"];
            imap_username: string;
            smtp_host: string;
            smtp_port: number;
            smtp_tls_mode: components["schemas"]["MailTLSMode"];
            smtp_username: string;
            /** @description Entra tenant id; null unless auth_kind is oauth_m365. */
            oauth_tenant_id: string | null;
            /** @description OAuth client id; null for basic-auth mailboxes. */
            oauth_client_id: string | null;
            /** @description From header display name ('' = use the mailbox name). */
            from_display_name: string;
            /** @description Appended to outbound mail ('' = none). */
            signature: string;
            /** @description Send the loop-guarded auto-acknowledgement for new tickets. */
            auto_ack_enabled: boolean;
            /**
             * Format: date-time
             * @description Last successful poll; null before the first success. Stays at
             *     the last success while errors occur, so "last worked at" is
             *     visible next to the error.
             */
            last_poll_at: string | null;
            /** @description Most recent poll/send error; null when healthy. */
            last_error: string | null;
            /**
             * Format: date-time
             * @description When last_error occurred; null when healthy.
             */
            last_error_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Writable connection/config fields shared by every mailbox create
         *     variant (credential fields live on the variants).
         */
        MailboxConfig: {
            name: string;
            /** Format: email */
            email_address: string;
            /** @default true */
            active: boolean;
            imap_host: string;
            imap_port: number;
            /** @default tls */
            imap_tls_mode: components["schemas"]["MailTLSMode"];
            imap_username: string;
            smtp_host: string;
            smtp_port: number;
            /** @default starttls */
            smtp_tls_mode: components["schemas"]["MailTLSMode"];
            smtp_username: string;
            /** @description Defaults to '' (the mailbox name is used). */
            from_display_name?: string;
            /** @description Defaults to ''. */
            signature?: string;
            /** @default true */
            auto_ack_enabled: boolean;
        };
        /** @description Password-authenticated IMAP/SMTP mailbox. */
        CreateMailboxBasicRequest: components["schemas"]["MailboxConfig"] & {
            /** @enum {string} */
            auth_kind: "basic";
            /**
             * @description IMAP/SMTP login password. Write-only: encrypted at rest,
             *     never returned by any response.
             */
            password: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            auth_kind: "basic";
        };
        /**
         * @description Microsoft 365 mailbox (Entra app registration, client-credentials
         *     XOAUTH2). Per-mailbox access is restricted Entra-side via
         *     application access policies.
         */
        CreateMailboxOauthM365Request: components["schemas"]["MailboxConfig"] & {
            /** @enum {string} */
            auth_kind: "oauth_m365";
            /**
             * @description Entra tenant id. Write-only here; echoed back (not
             *     secret) as `oauth_tenant_id`.
             */
            tenant_id: string;
            /**
             * @description App registration client id. Write-only here; echoed back
             *     (not secret) as `oauth_client_id`.
             */
            client_id: string;
            /**
             * @description App registration client secret. Write-only: encrypted at
             *     rest, never returned by any response.
             */
            client_secret: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            auth_kind: "oauth_m365";
        };
        /**
         * @description Google Workspace/Gmail mailbox (authorization-code XOAUTH2). The
         *     offline refresh token is NOT part of this request — after
         *     creating the mailbox, run `POST
         *     /mailboxes/{id}/oauth/google/start` and complete the browser
         *     consent flow; the callback stores the refresh token.
         */
        CreateMailboxOauthGoogleRequest: components["schemas"]["MailboxConfig"] & {
            /** @enum {string} */
            auth_kind: "oauth_google";
            /**
             * @description Google OAuth client id. Write-only here; echoed back (not
             *     secret) as `oauth_client_id`.
             */
            client_id: string;
            /**
             * @description Google OAuth client secret. Write-only: encrypted at
             *     rest, never returned by any response.
             */
            client_secret: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            auth_kind: "oauth_google";
        };
        /**
         * @description Mailbox creation payload, discriminated on `auth_kind`; each
         *     kind carries its own write-only credential fields.
         */
        CreateMailboxRequest: components["schemas"]["CreateMailboxBasicRequest"] | components["schemas"]["CreateMailboxOauthM365Request"] | components["schemas"]["CreateMailboxOauthGoogleRequest"];
        /**
         * @description Partial update; omitted fields are left unchanged. The write-only
         *     credential fields rotate stored secrets and are never echoed:
         *     `password` applies to `basic`; `tenant_id`, `client_id`,
         *     `client_secret` apply to the OAuth kinds. When `auth_kind`
         *     changes, the credential fields required by the new kind must be
         *     supplied in the same request (400 otherwise).
         */
        UpdateMailboxRequest: {
            name?: string;
            /** Format: email */
            email_address?: string;
            active?: boolean;
            auth_kind?: components["schemas"]["MailboxAuthKind"];
            imap_host?: string;
            imap_port?: number;
            imap_tls_mode?: components["schemas"]["MailTLSMode"];
            imap_username?: string;
            smtp_host?: string;
            smtp_port?: number;
            smtp_tls_mode?: components["schemas"]["MailTLSMode"];
            smtp_username?: string;
            from_display_name?: string;
            signature?: string;
            auto_ack_enabled?: boolean;
            /** @description New password (basic auth). Never echoed. */
            password?: string;
            /** @description New Entra tenant id (oauth_m365). */
            tenant_id?: string;
            /** @description New OAuth client id (oauth_m365 / oauth_google). */
            client_id?: string;
            /**
             * @description New OAuth client secret (oauth_m365 / oauth_google). Never
             *     echoed. Rotating an oauth_google client invalidates the
             *     stored refresh token — re-run the Google connect flow.
             */
            client_secret?: string;
        };
        /**
         * @description Outcome of a live mailbox connectivity test. `ok=false` still
         *     arrives as HTTP 200 — the test ran; this object is its result.
         */
        MailboxTestResult: {
            ok: boolean;
            /**
             * @description Human-readable outcome — the failing step and error on
             *     failure (e.g. "IMAP AUTHENTICATE: invalid credentials"), a
             *     short success summary otherwise.
             */
            detail: string;
            /**
             * Format: int64
             * @description Wall-clock duration of the whole test.
             */
            latency_ms: number;
        };
        MailboxTestSendRequest: {
            /**
             * Format: email
             * @description Recipient of the test message.
             */
            to: string;
        };
        /** @description Where to send the admin's browser to grant consent. */
        GoogleOauthStart: {
            /**
             * Format: uri
             * @description Google authorization URL (authorization-code flow with
             *     `access_type=offline`, signed single-use `state`).
             */
            authorization_url: string;
        };
        /** @description The instance's public base URL setting. */
        ExternalUrlSetting: {
            /**
             * @description Absolute http(s) base URL the instance is reached at, no
             *     trailing slash (e.g. "https://desk.example.com"); '' until
             *     configured.
             */
            external_url: string;
        };
        SetExternalUrlRequest: {
            /**
             * Format: uri
             * @description Absolute http(s) base URL with no path, query, or fragment;
             *     a trailing slash is stripped before storage.
             */
            external_url: string;
        };
    };
    responses: {
        /** @description Malformed request body or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, invalid, or expired session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated but not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request body exceeds the size limit (attachments: 25 MiB). */
        ContentTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Any other error, as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description User id. */
        UserID: string;
        /** @description Team id. */
        TeamID: string;
        /** @description Ticket id. */
        TicketID: string;
        /** @description Article id. */
        ArticleID: string;
        /** @description Attachment id. */
        AttachmentID: string;
        /** @description Tag id. */
        TagID: string;
        /** @description Mailbox id. */
        MailboxID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. Session cookie set. */
            204: {
                headers: {
                    /** @description `sd_session` signed HttpOnly session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid credentials or deactivated account. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Too many login attempts; retry later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared. */
            204: {
                headers: {
                    /** @description Expired `sd_session` cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user the session cookie belongs to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Problem"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Filter by role. */
                role?: components["schemas"]["Role"];
                /** @description Filter by active flag. */
                active?: boolean;
                /** @description Case-insensitive substring match against email and name. */
                q?: string;
                /** @description Page size. */
                limit?: number;
                /** @description Page offset. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching users, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A user with this email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    deactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User id. */
                id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All teams, sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Team created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A team with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The team, including member users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamWithMembers"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            /** @description The updated team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A team with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id. */
                id: components["parameters"]["TeamID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTeamMembersRequest"];
            };
        };
        responses: {
            /** @description The team with its new membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamWithMembers"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listTickets: {
        parameters: {
            query?: {
                /** @description Fixed workspace view applied before the other filters. */
                view?: components["schemas"]["TicketView"];
                /** @description Statuses to include (repeat the parameter). Empty = all. */
                status?: components["schemas"]["TicketStatus"][];
                /** @description Priorities to include (repeat the parameter). Empty = all. */
                priority?: components["schemas"]["TicketPriority"][];
                /** @description Only tickets assigned to this user. */
                assignee_id?: string;
                /** @description Only tickets owned by this team. */
                team_id?: string;
                /** @description Only tickets bearing this tag. */
                tag_id?: string;
                /**
                 * @description When true, only tickets closed since midnight (database
                 *     timezone) — the same predicate as the dashboard's
                 *     `closed_today` counter, so that tile can deep-link a queue
                 *     whose contents match its number.
                 */
                closed_today?: boolean;
                /**
                 * @description Full-text search (websearch syntax, e.g. `printer -toner` or
                 *     `"exact phrase"`) across ticket subjects and article bodies.
                 *     When present, results are ranked by relevance.
                 */
                q?: string;
                /** @description Page size. */
                limit?: number;
                /** @description Page offset. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of matching tickets plus the total match count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketRequest"];
            };
        };
        responses: {
            /** @description Ticket created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket id. */
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ticket detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket id. */
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketRequest"];
            };
        };
        responses: {
            /** @description The updated ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    setTicketTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket id. */
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTicketTagsRequest"];
            };
        };
        responses: {
            /** @description The ticket's new tag set, sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    createTicketArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket id. */
                id: components["parameters"]["TicketID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArticleRequest"];
            };
        };
        responses: {
            /** @description Article created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    uploadArticleAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article id. */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The file to attach (max 25 MiB).
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Attachment stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["ContentTooLarge"];
            default: components["responses"]["Problem"];
        };
    };
    retryArticleSend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article id. */
                id: components["parameters"]["ArticleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery re-enqueued; the article is `queued` again. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The article's delivery status is not `failed`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    downloadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attachment id. */
                id: components["parameters"]["AttachmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attachment body. */
            200: {
                headers: {
                    /** @description `attachment; filename="<sanitized>"`. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tags. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagRequest"];
            };
        };
        responses: {
            /** @description Tag created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A tag with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag id. */
                id: components["parameters"]["TagID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag id. */
                id: components["parameters"]["TagID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagRequest"];
            };
        };
        responses: {
            /** @description The updated tag. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A tag with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getDashboardCounters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current counter values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardCounters"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description The event stream (`text/event-stream`). The declared schema
             *     describes the JSON payload of each `data:` frame, not the raw
             *     stream body.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /**
             * @description Too many concurrent event streams on this server; retry
             *     later (the UI degrades gracefully — events only accelerate
             *     refetches).
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listMailboxes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All mailboxes, sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mailbox"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    createMailbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMailboxRequest"];
            };
        };
        responses: {
            /** @description Mailbox created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mailbox"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A mailbox with this email address already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMailbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mailbox id. */
                id: components["parameters"]["MailboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The mailbox. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mailbox"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    deleteMailbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mailbox id. */
                id: components["parameters"]["MailboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mailbox deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    updateMailbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mailbox id. */
                id: components["parameters"]["MailboxID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMailboxRequest"];
            };
        };
        responses: {
            /** @description The updated mailbox (credentials never included). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mailbox"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A mailbox with this email address already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    testMailboxFetch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mailbox id. */
                id: components["parameters"]["MailboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxTestResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    testMailboxSend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mailbox id. */
                id: components["parameters"]["MailboxID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailboxTestSendRequest"];
            };
        };
        responses: {
            /** @description Test outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailboxTestResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    startMailboxGoogleOauth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mailbox id. */
                id: components["parameters"]["MailboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authorization URL to send the admin's browser to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleOauthStart"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description The mailbox's `auth_kind` is not `oauth_google`, or the
             *     instance external URL setting is not configured (PUT
             *     /settings/external-url first).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    mailboxGoogleOauthCallback: {
        parameters: {
            query: {
                /** @description Signed single-use state minted by the start operation. */
                state: string;
                /** @description Authorization code (present on provider success). */
                code?: string;
                /** @description Provider error code (e.g. `access_denied`), if any. */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Refresh token stored; browser sent to
             *     `/settings/mailboxes?connected=1`.
             */
            303: {
                headers: {
                    /** @description `/settings/mailboxes?connected=1` */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    getExternalUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current setting. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalUrlSetting"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
    setExternalUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetExternalUrlRequest"];
            };
        };
        responses: {
            /** @description The stored (normalized) setting. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalUrlSetting"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            default: components["responses"]["Problem"];
        };
    };
}
