// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (name, key_prefix, key_hash, scopes, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, key_prefix, key_hash, scopes, created_by, last_used_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	Name      string    `json:"name"`
	KeyPrefix string    `json:"key_prefix"`
	KeyHash   string    `json:"key_hash"`
	Scopes    []string  `json:"scopes"`
	CreatedBy uuid.UUID `json:"created_by"`
}

// API keys: scoped machine credentials (M4). The plaintext key is never
// stored; only its SHA-256 hex digest (key_hash) is, and authentication is
// an exact-match lookup on that unique digest.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, name, key_prefix, scopes, created_by, last_used_at, created_at, revoked_at
FROM api_keys
WHERE id = $1
`

type GetAPIKeyRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	Scopes     []string           `json:"scopes"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetAPIKey(ctx context.Context, id uuid.UUID) (GetAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i GetAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.Scopes,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyForAuth = `-- name: GetAPIKeyForAuth :one
SELECT
    k.id           AS api_key_id,
    k.name         AS api_key_name,
    k.scopes       AS scopes,
    k.created_at   AS api_key_created_at,
    u.id           AS user_id,
    u.email        AS user_email,
    u.name         AS user_name,
    u.role         AS user_role,
    u.token_version AS user_token_version,
    u.active       AS user_active
FROM api_keys k
JOIN users u ON u.id = k.created_by
WHERE k.key_hash = $1
  AND k.revoked_at IS NULL
`

type GetAPIKeyForAuthRow struct {
	ApiKeyID         uuid.UUID `json:"api_key_id"`
	ApiKeyName       string    `json:"api_key_name"`
	Scopes           []string  `json:"scopes"`
	ApiKeyCreatedAt  time.Time `json:"api_key_created_at"`
	UserID           uuid.UUID `json:"user_id"`
	UserEmail        string    `json:"user_email"`
	UserName         string    `json:"user_name"`
	UserRole         UserRole  `json:"user_role"`
	UserTokenVersion int32     `json:"user_token_version"`
	UserActive       bool      `json:"user_active"`
}

// Authentication lookup: resolve a presented key's SHA-256 digest to the key
// (id, scopes) AND the acting user it was minted by, in one round trip. Only
// live (non-revoked) keys match. last_used_at is deliberately NOT touched
// here — call TouchAPIKey separately so the hot auth path stays a pure read.
func (q *Queries) GetAPIKeyForAuth(ctx context.Context, keyHash string) (GetAPIKeyForAuthRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyForAuth, keyHash)
	var i GetAPIKeyForAuthRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.ApiKeyName,
		&i.Scopes,
		&i.ApiKeyCreatedAt,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.UserRole,
		&i.UserTokenVersion,
		&i.UserActive,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, scopes, created_by, last_used_at, created_at, revoked_at
FROM api_keys
ORDER BY (revoked_at IS NOT NULL), created_at DESC
`

type ListAPIKeysRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	Scopes     []string           `json:"scopes"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

// Admin CRUD listing. Secrets never appear (no key_hash); the display prefix
// identifies each row. Live keys first, then revoked, newest first.
func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.Scopes,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

// Idempotent revoke: only flips a currently-live key. Zero rows affected =
// unknown or already revoked, which the handler maps to 404/no-op.
func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// Stamp last_used_at after a successful authenticated request. Kept separate
// from GetAPIKeyForAuth so it can be fired best-effort off the request path.
// Throttled to at most one write per key per minute: last_used_at is a coarse
// "recently seen" signal, not an access log, so a busy key polling at high QPS
// must not generate one same-row UPDATE (and dead-tuple churn) per request.
func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
