// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one

INSERT INTO articles (ticket_id, author_id, sender_type, channel, is_internal, body_text, body_html)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, ticket_id, author_id, sender_type, channel, is_internal, body_text, body_html, message_id, in_reply_to, references_header, delivery_status, created_at, search_tsv
`

type CreateArticleParams struct {
	TicketID   uuid.UUID      `json:"ticket_id"`
	AuthorID   pgtype.UUID    `json:"author_id"`
	SenderType ArticleSender  `json:"sender_type"`
	Channel    ArticleChannel `json:"channel"`
	IsInternal bool           `json:"is_internal"`
	BodyText   string         `json:"body_text"`
	BodyHtml   pgtype.Text    `json:"body_html"`
}

// Articles, attachments, and ticket events: M2 core.
// The email columns on articles (message_id, in_reply_to, references_header,
// delivery_status) are reserved for M3 and not written by any M2 query.
func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.TicketID,
		arg.AuthorID,
		arg.SenderType,
		arg.Channel,
		arg.IsInternal,
		arg.BodyText,
		arg.BodyHtml,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.SenderType,
		&i.Channel,
		&i.IsInternal,
		&i.BodyText,
		&i.BodyHtml,
		&i.MessageID,
		&i.InReplyTo,
		&i.ReferencesHeader,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.SearchTsv,
	)
	return i, err
}

const createArticleAttachment = `-- name: CreateArticleAttachment :one
INSERT INTO article_attachments (article_id, filename, content_type, size_bytes, storage_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, article_id, filename, content_type, size_bytes, storage_key, created_at
`

type CreateArticleAttachmentParams struct {
	ArticleID   uuid.UUID `json:"article_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
}

func (q *Queries) CreateArticleAttachment(ctx context.Context, arg CreateArticleAttachmentParams) (ArticleAttachment, error) {
	row := q.db.QueryRow(ctx, createArticleAttachment,
		arg.ArticleID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i ArticleAttachment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const createTicketEvent = `-- name: CreateTicketEvent :one
INSERT INTO ticket_events (ticket_id, actor_id, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, ticket_id, actor_id, type, payload, created_at
`

type CreateTicketEventParams struct {
	TicketID uuid.UUID   `json:"ticket_id"`
	ActorID  pgtype.UUID `json:"actor_id"`
	Type     string      `json:"type"`
	Payload  []byte      `json:"payload"`
}

func (q *Queries) CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) (TicketEvent, error) {
	row := q.db.QueryRow(ctx, createTicketEvent,
		arg.TicketID,
		arg.ActorID,
		arg.Type,
		arg.Payload,
	)
	var i TicketEvent
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.ActorID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArticleAttachment = `-- name: DeleteArticleAttachment :exec
DELETE FROM article_attachments
WHERE id = $1
`

func (q *Queries) DeleteArticleAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticleAttachment, id)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, ticket_id, author_id, sender_type, channel, is_internal, body_text, body_html, message_id, in_reply_to, references_header, delivery_status, created_at, search_tsv FROM articles
WHERE id = $1
`

func (q *Queries) GetArticle(ctx context.Context, id uuid.UUID) (Article, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.SenderType,
		&i.Channel,
		&i.IsInternal,
		&i.BodyText,
		&i.BodyHtml,
		&i.MessageID,
		&i.InReplyTo,
		&i.ReferencesHeader,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.SearchTsv,
	)
	return i, err
}

const getArticleAttachment = `-- name: GetArticleAttachment :one
SELECT id, article_id, filename, content_type, size_bytes, storage_key, created_at FROM article_attachments
WHERE id = $1
`

func (q *Queries) GetArticleAttachment(ctx context.Context, id uuid.UUID) (ArticleAttachment, error) {
	row := q.db.QueryRow(ctx, getArticleAttachment, id)
	var i ArticleAttachment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listArticleAttachments = `-- name: ListArticleAttachments :many
SELECT id, article_id, filename, content_type, size_bytes, storage_key, created_at FROM article_attachments
WHERE article_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListArticleAttachments(ctx context.Context, articleID uuid.UUID) ([]ArticleAttachment, error) {
	rows, err := q.db.Query(ctx, listArticleAttachments, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArticleAttachment
	for rows.Next() {
		var i ArticleAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByTicket = `-- name: ListArticlesByTicket :many
SELECT a.id, a.ticket_id, a.author_id, a.sender_type, a.channel, a.is_internal, a.body_text, a.body_html, a.message_id, a.in_reply_to, a.references_header, a.delivery_status, a.created_at, a.search_tsv,
       COALESCE(author.name, '')        AS author_name,
       COALESCE(author.email::text, '') AS author_email
FROM articles a
LEFT JOIN users author ON author.id = a.author_id
WHERE a.ticket_id = $1
ORDER BY a.created_at, a.id
`

type ListArticlesByTicketRow struct {
	Article     Article     `json:"article"`
	AuthorName  string      `json:"author_name"`
	AuthorEmail interface{} `json:"author_email"`
}

func (q *Queries) ListArticlesByTicket(ctx context.Context, ticketID uuid.UUID) ([]ListArticlesByTicketRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesByTicketRow
	for rows.Next() {
		var i ListArticlesByTicketRow
		if err := rows.Scan(
			&i.Article.ID,
			&i.Article.TicketID,
			&i.Article.AuthorID,
			&i.Article.SenderType,
			&i.Article.Channel,
			&i.Article.IsInternal,
			&i.Article.BodyText,
			&i.Article.BodyHtml,
			&i.Article.MessageID,
			&i.Article.InReplyTo,
			&i.Article.ReferencesHeader,
			&i.Article.DeliveryStatus,
			&i.Article.CreatedAt,
			&i.Article.SearchTsv,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForTicket = `-- name: ListAttachmentsForTicket :many
SELECT aa.id, aa.article_id, aa.filename, aa.content_type, aa.size_bytes, aa.storage_key, aa.created_at FROM article_attachments aa
JOIN articles a ON a.id = aa.article_id
WHERE a.ticket_id = $1
ORDER BY aa.created_at, aa.id
`

func (q *Queries) ListAttachmentsForTicket(ctx context.Context, ticketID uuid.UUID) ([]ArticleAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArticleAttachment
	for rows.Next() {
		var i ArticleAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketEvents = `-- name: ListTicketEvents :many
SELECT id, ticket_id, actor_id, type, payload, created_at FROM ticket_events
WHERE ticket_id = $1
ORDER BY id
`

// Ordered by the identity pk: insertion order, stable even within one
// transaction (where created_at ties).
func (q *Queries) ListTicketEvents(ctx context.Context, ticketID uuid.UUID) ([]TicketEvent, error) {
	rows, err := q.db.Query(ctx, listTicketEvents, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketEvent
	for rows.Next() {
		var i TicketEvent
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.ActorID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
