// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canned_replies.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createCannedReply = `-- name: CreateCannedReply :one

INSERT INTO canned_replies (title, body, created_by)
VALUES ($1, $2, $3)
RETURNING id, title, body, created_by, created_at, updated_at
`

type CreateCannedReplyParams struct {
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	CreatedBy uuid.UUID `json:"created_by"`
}

// Canned replies: reusable agent snippets (M4). Variable substitution
// ({{ticket.number}}, {{requester.name}}) happens in the service layer when a
// reply is inserted into the composer; the stored body keeps the raw template.
func (q *Queries) CreateCannedReply(ctx context.Context, arg CreateCannedReplyParams) (CannedReply, error) {
	row := q.db.QueryRow(ctx, createCannedReply, arg.Title, arg.Body, arg.CreatedBy)
	var i CannedReply
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCannedReply = `-- name: DeleteCannedReply :execrows
DELETE FROM canned_replies
WHERE id = $1
`

func (q *Queries) DeleteCannedReply(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCannedReply, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCannedReply = `-- name: GetCannedReply :one
SELECT id, title, body, created_by, created_at, updated_at FROM canned_replies
WHERE id = $1
`

func (q *Queries) GetCannedReply(ctx context.Context, id uuid.UUID) (CannedReply, error) {
	row := q.db.QueryRow(ctx, getCannedReply, id)
	var i CannedReply
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCannedReplies = `-- name: ListCannedReplies :many
SELECT id, title, body, created_by, created_at, updated_at FROM canned_replies
ORDER BY title, id
`

func (q *Queries) ListCannedReplies(ctx context.Context) ([]CannedReply, error) {
	rows, err := q.db.Query(ctx, listCannedReplies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CannedReply
	for rows.Next() {
		var i CannedReply
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCannedReply = `-- name: UpdateCannedReply :one
UPDATE canned_replies
SET title      = $2,
    body       = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, title, body, created_by, created_at, updated_at
`

type UpdateCannedReplyParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
	Body  string    `json:"body"`
}

func (q *Queries) UpdateCannedReply(ctx context.Context, arg UpdateCannedReplyParams) (CannedReply, error) {
	row := q.db.QueryRow(ctx, updateCannedReply, arg.ID, arg.Title, arg.Body)
	var i CannedReply
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
