// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_message_ids.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEmailMessageID = `-- name: GetEmailMessageID :one
SELECT message_id, direction, mailbox_id, ticket_id, article_id, created_at FROM email_message_ids
WHERE message_id = $1
`

func (q *Queries) GetEmailMessageID(ctx context.Context, messageID string) (EmailMessageID, error) {
	row := q.db.QueryRow(ctx, getEmailMessageID, messageID)
	var i EmailMessageID
	err := row.Scan(
		&i.MessageID,
		&i.Direction,
		&i.MailboxID,
		&i.TicketID,
		&i.ArticleID,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmailMessageID = `-- name: InsertEmailMessageID :execrows

INSERT INTO email_message_ids (message_id, direction, mailbox_id, ticket_id, article_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (message_id) DO NOTHING
`

type InsertEmailMessageIDParams struct {
	MessageID string         `json:"message_id"`
	Direction EmailDirection `json:"direction"`
	MailboxID pgtype.UUID    `json:"mailbox_id"`
	TicketID  uuid.UUID      `json:"ticket_id"`
	ArticleID pgtype.UUID    `json:"article_id"`
}

// email_message_ids: every inbound and outbound Message-ID (dedup +
// threading, architecture doc §4).
// Returns 0 rows on Message-ID conflict: an inbound redelivery. Callers
// treat 0 as "already ingested" and skip the message — this is what makes
// at-least-once IMAP delivery exactly-once.
func (q *Queries) InsertEmailMessageID(ctx context.Context, arg InsertEmailMessageIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEmailMessageID,
		arg.MessageID,
		arg.Direction,
		arg.MailboxID,
		arg.TicketID,
		arg.ArticleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestInboundMailboxForTicket = `-- name: LatestInboundMailboxForTicket :one
SELECT m.id, m.name, m.email_address, m.active, m.auth_kind, m.imap_host, m.imap_port, m.imap_tls_mode, m.imap_username, m.smtp_host, m.smtp_port, m.smtp_tls_mode, m.smtp_username, m.credentials_enc, m.oauth_tenant_id, m.oauth_client_id, m.from_display_name, m.signature, m.auto_ack_enabled, m.last_poll_at, m.last_error, m.last_error_at, m.created_at, m.updated_at FROM email_message_ids e
JOIN mailboxes m ON m.id = e.mailbox_id
WHERE e.ticket_id = $1 AND e.direction = 'inbound'
ORDER BY e.created_at DESC, e.message_id
LIMIT 1
`

// The mailbox a ticket's email conversation lives on: the mailbox that
// received the most recent inbound message. No row = not an email-origin
// ticket (or its mailbox was deleted).
func (q *Queries) LatestInboundMailboxForTicket(ctx context.Context, ticketID uuid.UUID) (Mailbox, error) {
	row := q.db.QueryRow(ctx, latestInboundMailboxForTicket, ticketID)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.Active,
		&i.AuthKind,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapTlsMode,
		&i.ImapUsername,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTlsMode,
		&i.SmtpUsername,
		&i.CredentialsEnc,
		&i.OauthTenantID,
		&i.OauthClientID,
		&i.FromDisplayName,
		&i.Signature,
		&i.AutoAckEnabled,
		&i.LastPollAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestInboundMessageIDForTicket = `-- name: LatestInboundMessageIDForTicket :one
SELECT message_id, direction, mailbox_id, ticket_id, article_id, created_at FROM email_message_ids
WHERE ticket_id = $1 AND direction = 'inbound'
ORDER BY created_at DESC, message_id
LIMIT 1
`

// The Message-ID an outbound reply answers (In-Reply-To header).
func (q *Queries) LatestInboundMessageIDForTicket(ctx context.Context, ticketID uuid.UUID) (EmailMessageID, error) {
	row := q.db.QueryRow(ctx, latestInboundMessageIDForTicket, ticketID)
	var i EmailMessageID
	err := row.Scan(
		&i.MessageID,
		&i.Direction,
		&i.MailboxID,
		&i.TicketID,
		&i.ArticleID,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentEmailMessageIDsByTicket = `-- name: ListRecentEmailMessageIDsByTicket :many
SELECT message_id, direction, mailbox_id, ticket_id, article_id, created_at FROM email_message_ids
WHERE ticket_id = $1
ORDER BY created_at DESC, message_id
LIMIT $2
`

type ListRecentEmailMessageIDsByTicketParams struct {
	TicketID uuid.UUID `json:"ticket_id"`
	Limit    int32     `json:"limit"`
}

// Newest-first with a cap; used to walk References chains (threading) and
// to build the References header for outbound replies (callers reverse
// into oldest-first header order).
func (q *Queries) ListRecentEmailMessageIDsByTicket(ctx context.Context, arg ListRecentEmailMessageIDsByTicketParams) ([]EmailMessageID, error) {
	rows, err := q.db.Query(ctx, listRecentEmailMessageIDsByTicket, arg.TicketID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailMessageID
	for rows.Next() {
		var i EmailMessageID
		if err := rows.Scan(
			&i.MessageID,
			&i.Direction,
			&i.MailboxID,
			&i.TicketID,
			&i.ArticleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
