// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailbox_leases.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const claimMailboxLease = `-- name: ClaimMailboxLease :one

INSERT INTO mailbox_leases (mailbox_id, owner, expires_at)
VALUES (
    $1,
    $2,
    now() + make_interval(secs => $3::float8)
)
ON CONFLICT (mailbox_id) DO UPDATE
SET owner      = EXCLUDED.owner,
    expires_at = EXCLUDED.expires_at
WHERE mailbox_leases.expires_at < now()
   OR mailbox_leases.owner = EXCLUDED.owner
RETURNING mailbox_id, owner, expires_at
`

type ClaimMailboxLeaseParams struct {
	MailboxID  uuid.UUID `json:"mailbox_id"`
	Owner      string    `json:"owner"`
	TtlSeconds float64   `json:"ttl_seconds"`
}

// Mailbox ownership leases (architecture doc §4: leader-elected lease per
// mailbox; on worker death the lease lapses and another worker adopts).
// All expiry math uses the database clock so N app nodes need no clock
// agreement.
// Atomic claim-or-takeover. Succeeds (returns the lease) when the mailbox
// is unleased, the existing lease has expired, or the caller already owns
// it (re-claim extends). Otherwise no row is updated and the caller gets
// pgx.ErrNoRows: somebody else holds a live lease.
func (q *Queries) ClaimMailboxLease(ctx context.Context, arg ClaimMailboxLeaseParams) (MailboxLease, error) {
	row := q.db.QueryRow(ctx, claimMailboxLease, arg.MailboxID, arg.Owner, arg.TtlSeconds)
	var i MailboxLease
	err := row.Scan(&i.MailboxID, &i.Owner, &i.ExpiresAt)
	return i, err
}

const releaseMailboxLease = `-- name: ReleaseMailboxLease :execrows
DELETE FROM mailbox_leases
WHERE mailbox_id = $1
  AND owner = $2
`

type ReleaseMailboxLeaseParams struct {
	MailboxID uuid.UUID `json:"mailbox_id"`
	Owner     string    `json:"owner"`
}

// Graceful shutdown: drop the lease so another worker can adopt the
// mailbox immediately instead of waiting out the TTL. Owner-checked, so
// releasing a lease lost to takeover is a harmless 0-row no-op.
func (q *Queries) ReleaseMailboxLease(ctx context.Context, arg ReleaseMailboxLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseMailboxLease, arg.MailboxID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewMailboxLease = `-- name: RenewMailboxLease :one
UPDATE mailbox_leases
SET expires_at = now() + make_interval(secs => $1::float8)
WHERE mailbox_id = $2
  AND owner = $3
RETURNING mailbox_id, owner, expires_at
`

type RenewMailboxLeaseParams struct {
	TtlSeconds float64   `json:"ttl_seconds"`
	MailboxID  uuid.UUID `json:"mailbox_id"`
	Owner      string    `json:"owner"`
}

// Extend a lease we still hold. pgx.ErrNoRows means the lease expired and
// was taken over (or released): the caller must stop polling this mailbox.
// The owner check makes renewal safe even after a takeover; expiry is NOT
// checked so a briefly-late renewal keeps the lease if nobody took it.
func (q *Queries) RenewMailboxLease(ctx context.Context, arg RenewMailboxLeaseParams) (MailboxLease, error) {
	row := q.db.QueryRow(ctx, renewMailboxLease, arg.TtlSeconds, arg.MailboxID, arg.Owner)
	var i MailboxLease
	err := row.Scan(&i.MailboxID, &i.Owner, &i.ExpiresAt)
	return i, err
}
