// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ArticleChannel string

const (
	ArticleChannelEmail ArticleChannel = "email"
	ArticleChannelApi   ArticleChannel = "api"
	ArticleChannelWeb   ArticleChannel = "web"
)

func (e *ArticleChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArticleChannel(s)
	case string:
		*e = ArticleChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for ArticleChannel: %T", src)
	}
	return nil
}

type NullArticleChannel struct {
	ArticleChannel ArticleChannel `json:"article_channel"`
	Valid          bool           `json:"valid"` // Valid is true if ArticleChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArticleChannel) Scan(value interface{}) error {
	if value == nil {
		ns.ArticleChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArticleChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArticleChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArticleChannel), nil
}

type ArticleSender string

const (
	ArticleSenderCustomer ArticleSender = "customer"
	ArticleSenderAgent    ArticleSender = "agent"
	ArticleSenderSystem   ArticleSender = "system"
)

func (e *ArticleSender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArticleSender(s)
	case string:
		*e = ArticleSender(s)
	default:
		return fmt.Errorf("unsupported scan type for ArticleSender: %T", src)
	}
	return nil
}

type NullArticleSender struct {
	ArticleSender ArticleSender `json:"article_sender"`
	Valid         bool          `json:"valid"` // Valid is true if ArticleSender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArticleSender) Scan(value interface{}) error {
	if value == nil {
		ns.ArticleSender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArticleSender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArticleSender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArticleSender), nil
}

type EmailDirection string

const (
	EmailDirectionInbound  EmailDirection = "inbound"
	EmailDirectionOutbound EmailDirection = "outbound"
)

func (e *EmailDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmailDirection(s)
	case string:
		*e = EmailDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for EmailDirection: %T", src)
	}
	return nil
}

type NullEmailDirection struct {
	EmailDirection EmailDirection `json:"email_direction"`
	Valid          bool           `json:"valid"` // Valid is true if EmailDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmailDirection) Scan(value interface{}) error {
	if value == nil {
		ns.EmailDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmailDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmailDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmailDirection), nil
}

type MailTlsMode string

const (
	MailTlsModeTls      MailTlsMode = "tls"
	MailTlsModeStarttls MailTlsMode = "starttls"
	MailTlsModeNone     MailTlsMode = "none"
)

func (e *MailTlsMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MailTlsMode(s)
	case string:
		*e = MailTlsMode(s)
	default:
		return fmt.Errorf("unsupported scan type for MailTlsMode: %T", src)
	}
	return nil
}

type NullMailTlsMode struct {
	MailTlsMode MailTlsMode `json:"mail_tls_mode"`
	Valid       bool        `json:"valid"` // Valid is true if MailTlsMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMailTlsMode) Scan(value interface{}) error {
	if value == nil {
		ns.MailTlsMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MailTlsMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMailTlsMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MailTlsMode), nil
}

type MailboxAuthKind string

const (
	MailboxAuthKindBasic       MailboxAuthKind = "basic"
	MailboxAuthKindOauthM365   MailboxAuthKind = "oauth_m365"
	MailboxAuthKindOauthGoogle MailboxAuthKind = "oauth_google"
)

func (e *MailboxAuthKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MailboxAuthKind(s)
	case string:
		*e = MailboxAuthKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MailboxAuthKind: %T", src)
	}
	return nil
}

type NullMailboxAuthKind struct {
	MailboxAuthKind MailboxAuthKind `json:"mailbox_auth_kind"`
	Valid           bool            `json:"valid"` // Valid is true if MailboxAuthKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMailboxAuthKind) Scan(value interface{}) error {
	if value == nil {
		ns.MailboxAuthKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MailboxAuthKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMailboxAuthKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MailboxAuthKind), nil
}

type TicketPriority string

const (
	TicketPriorityLow      TicketPriority = "low"
	TicketPriorityMedium   TicketPriority = "medium"
	TicketPriorityHigh     TicketPriority = "high"
	TicketPriorityCritical TicketPriority = "critical"
)

func (e *TicketPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketPriority(s)
	case string:
		*e = TicketPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketPriority: %T", src)
	}
	return nil
}

type NullTicketPriority struct {
	TicketPriority TicketPriority `json:"ticket_priority"`
	Valid          bool           `json:"valid"` // Valid is true if TicketPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TicketPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketPriority), nil
}

type TicketStatus string

const (
	TicketStatusOpen              TicketStatus = "open"
	TicketStatusWaitingOnCustomer TicketStatus = "waiting_on_customer"
	TicketStatusOnHold            TicketStatus = "on_hold"
	TicketStatusClosed            TicketStatus = "closed"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus `json:"ticket_status"`
	Valid        bool         `json:"valid"` // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleAgent    UserRole = "agent"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WebhookDeliveryStatus string

const (
	WebhookDeliveryStatusPending WebhookDeliveryStatus = "pending"
	WebhookDeliveryStatusSuccess WebhookDeliveryStatus = "success"
	WebhookDeliveryStatusFailed  WebhookDeliveryStatus = "failed"
)

func (e *WebhookDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookDeliveryStatus(s)
	case string:
		*e = WebhookDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookDeliveryStatus: %T", src)
	}
	return nil
}

type NullWebhookDeliveryStatus struct {
	WebhookDeliveryStatus WebhookDeliveryStatus `json:"webhook_delivery_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if WebhookDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookDeliveryStatus), nil
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	Scopes     []string           `json:"scopes"`
	CreatedBy  uuid.UUID          `json:"created_by"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Article struct {
	ID               uuid.UUID      `json:"id"`
	TicketID         uuid.UUID      `json:"ticket_id"`
	AuthorID         pgtype.UUID    `json:"author_id"`
	SenderType       ArticleSender  `json:"sender_type"`
	Channel          ArticleChannel `json:"channel"`
	IsInternal       bool           `json:"is_internal"`
	BodyText         string         `json:"body_text"`
	BodyHtml         pgtype.Text    `json:"body_html"`
	MessageID        pgtype.Text    `json:"message_id"`
	InReplyTo        pgtype.Text    `json:"in_reply_to"`
	ReferencesHeader pgtype.Text    `json:"references_header"`
	DeliveryStatus   pgtype.Text    `json:"delivery_status"`
	CreatedAt        time.Time      `json:"created_at"`
	SearchTsv        string         `json:"search_tsv"`
}

type ArticleAttachment struct {
	ID          uuid.UUID `json:"id"`
	ArticleID   uuid.UUID `json:"article_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type CannedReply struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type EmailMessageID struct {
	MessageID string         `json:"message_id"`
	Direction EmailDirection `json:"direction"`
	MailboxID pgtype.UUID    `json:"mailbox_id"`
	TicketID  uuid.UUID      `json:"ticket_id"`
	ArticleID pgtype.UUID    `json:"article_id"`
	CreatedAt time.Time      `json:"created_at"`
}

type Mailbox struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	EmailAddress    string             `json:"email_address"`
	Active          bool               `json:"active"`
	AuthKind        MailboxAuthKind    `json:"auth_kind"`
	ImapHost        string             `json:"imap_host"`
	ImapPort        int32              `json:"imap_port"`
	ImapTlsMode     MailTlsMode        `json:"imap_tls_mode"`
	ImapUsername    string             `json:"imap_username"`
	SmtpHost        string             `json:"smtp_host"`
	SmtpPort        int32              `json:"smtp_port"`
	SmtpTlsMode     MailTlsMode        `json:"smtp_tls_mode"`
	SmtpUsername    string             `json:"smtp_username"`
	CredentialsEnc  string             `json:"credentials_enc"`
	OauthTenantID   pgtype.Text        `json:"oauth_tenant_id"`
	OauthClientID   pgtype.Text        `json:"oauth_client_id"`
	FromDisplayName string             `json:"from_display_name"`
	Signature       string             `json:"signature"`
	AutoAckEnabled  bool               `json:"auto_ack_enabled"`
	LastPollAt      pgtype.Timestamptz `json:"last_poll_at"`
	LastError       pgtype.Text        `json:"last_error"`
	LastErrorAt     pgtype.Timestamptz `json:"last_error_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type MailboxLease struct {
	MailboxID uuid.UUID `json:"mailbox_id"`
	Owner     string    `json:"owner"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

type Tag struct {
	ID    uuid.UUID   `json:"id"`
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

type Team struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type TeamMember struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

type Ticket struct {
	ID          uuid.UUID          `json:"id"`
	Number      string             `json:"number"`
	Subject     string             `json:"subject"`
	Status      TicketStatus       `json:"status"`
	Priority    TicketPriority     `json:"priority"`
	RequesterID uuid.UUID          `json:"requester_id"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
	SearchTsv   string             `json:"search_tsv"`
}

type TicketEvent struct {
	ID        int64       `json:"id"`
	TicketID  uuid.UUID   `json:"ticket_id"`
	ActorID   pgtype.UUID `json:"actor_id"`
	Type      string      `json:"type"`
	Payload   []byte      `json:"payload"`
	CreatedAt time.Time   `json:"created_at"`
}

type TicketNumberCounter struct {
	Day     time.Time `json:"day"`
	Counter int32     `json:"counter"`
}

type TicketTag struct {
	TicketID uuid.UUID `json:"ticket_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Role         UserRole    `json:"role"`
	PasswordHash pgtype.Text `json:"password_hash"`
	OidcIssuer   pgtype.Text `json:"oidc_issuer"`
	OidcSubject  pgtype.Text `json:"oidc_subject"`
	Company      string      `json:"company"`
	TokenVersion int32       `json:"token_version"`
	Active       bool        `json:"active"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Webhook struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Url       string    `json:"url"`
	SecretEnc string    `json:"secret_enc"`
	Events    []string  `json:"events"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WebhookDelivery struct {
	ID           int64                 `json:"id"`
	WebhookID    uuid.UUID             `json:"webhook_id"`
	EventType    string                `json:"event_type"`
	TicketID     pgtype.UUID           `json:"ticket_id"`
	Payload      []byte                `json:"payload"`
	Status       WebhookDeliveryStatus `json:"status"`
	ResponseCode pgtype.Int4           `json:"response_code"`
	Attempts     int32                 `json:"attempts"`
	LastError    pgtype.Text           `json:"last_error"`
	CreatedAt    time.Time             `json:"created_at"`
	DeliveredAt  pgtype.Timestamptz    `json:"delivered_at"`
}
