// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTicketTags = `-- name: AddTicketTags :exec
INSERT INTO ticket_tags (ticket_id, tag_id)
SELECT $1::uuid, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AddTicketTagsParams struct {
	TicketID uuid.UUID   `json:"ticket_id"`
	TagIds   []uuid.UUID `json:"tag_ids"`
}

func (q *Queries) AddTicketTags(ctx context.Context, arg AddTicketTagsParams) error {
	_, err := q.db.Exec(ctx, addTicketTags, arg.TicketID, arg.TagIds)
	return err
}

const clearTicketTags = `-- name: ClearTicketTags :exec
DELETE FROM ticket_tags
WHERE ticket_id = $1
`

// Set-ticket-tags is clear + bulk insert inside the service transaction.
func (q *Queries) ClearTicketTags(ctx context.Context, ticketID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTicketTags, ticketID)
	return err
}

const countTagsByIDs = `-- name: CountTagsByIDs :one
SELECT count(*) FROM tags
WHERE id = ANY ($1::uuid[])
`

// Existence check used by SetTags to reject unknown tag ids up front.
func (q *Queries) CountTagsByIDs(ctx context.Context, tagIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTagsByIDs, tagIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (name, color)
VALUES ($1, $2)
RETURNING id, name, color
`

type CreateTagParams struct {
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

// Tags and ticket_tags: M2 core.
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, color FROM tags
WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, color FROM tags
WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, color FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTicket = `-- name: ListTagsForTicket :many
SELECT tg.id, tg.name, tg.color FROM tags tg
JOIN ticket_tags tt ON tt.tag_id = tg.id
WHERE tt.ticket_id = $1
ORDER BY tg.name
`

func (q *Queries) ListTagsForTicket(ctx context.Context, ticketID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name  = $2,
    color = $3
WHERE id = $1
RETURNING id, name, color
`

type UpdateTagParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}
