// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (number, subject, status, priority, requester_id, assignee_id, team_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, number, subject, status, priority, requester_id, assignee_id, team_id, created_at, updated_at, closed_at, search_tsv
`

type CreateTicketParams struct {
	Number      string         `json:"number"`
	Subject     string         `json:"subject"`
	Status      TicketStatus   `json:"status"`
	Priority    TicketPriority `json:"priority"`
	RequesterID uuid.UUID      `json:"requester_id"`
	AssigneeID  pgtype.UUID    `json:"assignee_id"`
	TeamID      pgtype.UUID    `json:"team_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Number,
		arg.Subject,
		arg.Status,
		arg.Priority,
		arg.RequesterID,
		arg.AssigneeID,
		arg.TeamID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.RequesterID,
		&i.AssigneeID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SearchTsv,
	)
	return i, err
}

const dashboardCounts = `-- name: DashboardCounts :one
SELECT count(*) FILTER (WHERE status = 'open')                                   AS open_count,
       count(*) FILTER (WHERE status <> 'closed' AND assignee_id IS NULL)        AS unassigned_count,
       count(*) FILTER (WHERE status = 'waiting_on_customer')                    AS waiting_on_customer_count,
       count(*) FILTER (WHERE status = 'closed' AND closed_at >= date_trunc('day', now())) AS closed_today_count
FROM tickets
`

type DashboardCountsRow struct {
	OpenCount              int64 `json:"open_count"`
	UnassignedCount        int64 `json:"unassigned_count"`
	WaitingOnCustomerCount int64 `json:"waiting_on_customer_count"`
	ClosedTodayCount       int64 `json:"closed_today_count"`
}

// The four dashboard counters in one scan. "Closed today" is measured in
// the database's timezone (UTC in deployment).
func (q *Queries) DashboardCounts(ctx context.Context) (DashboardCountsRow, error) {
	row := q.db.QueryRow(ctx, dashboardCounts)
	var i DashboardCountsRow
	err := row.Scan(
		&i.OpenCount,
		&i.UnassignedCount,
		&i.WaitingOnCustomerCount,
		&i.ClosedTodayCount,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT t.id, t.number, t.subject, t.status, t.priority, t.requester_id, t.assignee_id, t.team_id, t.created_at, t.updated_at, t.closed_at, t.search_tsv,
       requester.name  AS requester_name,
       requester.email AS requester_email,
       COALESCE(assignee.name, '')         AS assignee_name,
       COALESCE(assignee.email::text, '')  AS assignee_email
FROM tickets t
JOIN users requester ON requester.id = t.requester_id
LEFT JOIN users assignee ON assignee.id = t.assignee_id
WHERE t.id = $1
`

type GetTicketRow struct {
	Ticket         Ticket      `json:"ticket"`
	RequesterName  string      `json:"requester_name"`
	RequesterEmail string      `json:"requester_email"`
	AssigneeName   string      `json:"assignee_name"`
	AssigneeEmail  interface{} `json:"assignee_email"`
}

// Ticket with requester and assignee display fields joined in.
func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.Ticket.ID,
		&i.Ticket.Number,
		&i.Ticket.Subject,
		&i.Ticket.Status,
		&i.Ticket.Priority,
		&i.Ticket.RequesterID,
		&i.Ticket.AssigneeID,
		&i.Ticket.TeamID,
		&i.Ticket.CreatedAt,
		&i.Ticket.UpdatedAt,
		&i.Ticket.ClosedAt,
		&i.Ticket.SearchTsv,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.AssigneeName,
		&i.AssigneeEmail,
	)
	return i, err
}

const getTicketByNumber = `-- name: GetTicketByNumber :one
SELECT t.id, t.number, t.subject, t.status, t.priority, t.requester_id, t.assignee_id, t.team_id, t.created_at, t.updated_at, t.closed_at, t.search_tsv,
       requester.name  AS requester_name,
       requester.email AS requester_email,
       COALESCE(assignee.name, '')         AS assignee_name,
       COALESCE(assignee.email::text, '')  AS assignee_email
FROM tickets t
JOIN users requester ON requester.id = t.requester_id
LEFT JOIN users assignee ON assignee.id = t.assignee_id
WHERE t.number = $1
`

type GetTicketByNumberRow struct {
	Ticket         Ticket      `json:"ticket"`
	RequesterName  string      `json:"requester_name"`
	RequesterEmail string      `json:"requester_email"`
	AssigneeName   string      `json:"assignee_name"`
	AssigneeEmail  interface{} `json:"assignee_email"`
}

func (q *Queries) GetTicketByNumber(ctx context.Context, number string) (GetTicketByNumberRow, error) {
	row := q.db.QueryRow(ctx, getTicketByNumber, number)
	var i GetTicketByNumberRow
	err := row.Scan(
		&i.Ticket.ID,
		&i.Ticket.Number,
		&i.Ticket.Subject,
		&i.Ticket.Status,
		&i.Ticket.Priority,
		&i.Ticket.RequesterID,
		&i.Ticket.AssigneeID,
		&i.Ticket.TeamID,
		&i.Ticket.CreatedAt,
		&i.Ticket.UpdatedAt,
		&i.Ticket.ClosedAt,
		&i.Ticket.SearchTsv,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.AssigneeName,
		&i.AssigneeEmail,
	)
	return i, err
}

const getTicketForUpdate = `-- name: GetTicketForUpdate :one
SELECT id, number, subject, status, priority, requester_id, assignee_id, team_id, created_at, updated_at, closed_at, search_tsv FROM tickets
WHERE id = $1
FOR UPDATE
`

// Row-locked read used inside service transactions that decide on a state
// change (e.g. the add-article status matrix) so concurrent writers
// serialize instead of racing.
func (q *Queries) GetTicketForUpdate(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketForUpdate, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.RequesterID,
		&i.AssigneeID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SearchTsv,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT t.id, t.number, t.subject, t.status, t.priority, t.requester_id, t.assignee_id, t.team_id, t.created_at, t.updated_at, t.closed_at, t.search_tsv,
       requester.name  AS requester_name,
       requester.email AS requester_email,
       COALESCE(assignee.name, '')         AS assignee_name,
       COALESCE(assignee.email::text, '')  AS assignee_email,
       count(*) OVER () AS total_count
FROM tickets t
JOIN users requester ON requester.id = t.requester_id
LEFT JOIN users assignee ON assignee.id = t.assignee_id
WHERE (COALESCE(cardinality($1::text[]), 0) = 0 OR t.status::text = ANY ($1::text[]))
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR t.priority::text = ANY ($2::text[]))
  AND ($3::uuid IS NULL OR t.assignee_id = $3::uuid)
  AND (NOT COALESCE($4::boolean, false) OR t.assignee_id IS NULL)
  AND ($5::uuid IS NULL OR t.team_id = $5::uuid)
  AND ($6::uuid IS NULL OR t.requester_id = $6::uuid)
  AND ($7::uuid IS NULL OR EXISTS (
        SELECT 1 FROM ticket_tags tt
        WHERE tt.ticket_id = t.id AND tt.tag_id = $7::uuid))
  -- closed_today mirrors the DashboardCounts closed-today predicate so the
  -- dashboard tile can deep-link a queue that matches its number.
  AND (NOT COALESCE($8::boolean, false)
       OR (t.status = 'closed' AND t.closed_at >= date_trunc('day', now())))
ORDER BY t.updated_at DESC, t.id
LIMIT $10::bigint
OFFSET $9::bigint
`

type ListTicketsParams struct {
	Statuses    []string    `json:"statuses"`
	Priorities  []string    `json:"priorities"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	Unassigned  pgtype.Bool `json:"unassigned"`
	TeamID      pgtype.UUID `json:"team_id"`
	RequesterID pgtype.UUID `json:"requester_id"`
	TagID       pgtype.UUID `json:"tag_id"`
	ClosedToday pgtype.Bool `json:"closed_today"`
	PageOffset  int64       `json:"page_offset"`
	PageLimit   int64       `json:"page_limit"`
}

type ListTicketsRow struct {
	Ticket         Ticket      `json:"ticket"`
	RequesterName  string      `json:"requester_name"`
	RequesterEmail string      `json:"requester_email"`
	AssigneeName   string      `json:"assignee_name"`
	AssigneeEmail  interface{} `json:"assignee_email"`
	TotalCount     int64       `json:"total_count"`
}

// Filtered ticket list for the fixed views and ad-hoc combos:
//
//	statuses:   empty array = all statuses ("All open" passes the 3 open-ish ones)
//	priorities: empty array = all priorities
//	assignee_id: "My tickets"; unassigned=true: "Unassigned"
//	team_id / requester_id / tag_id: optional narrowing
//
// total_count is the pre-LIMIT match count (window function), so one
// round-trip serves both the page and the pager.
func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.Query(ctx, listTickets,
		arg.Statuses,
		arg.Priorities,
		arg.AssigneeID,
		arg.Unassigned,
		arg.TeamID,
		arg.RequesterID,
		arg.TagID,
		arg.ClosedToday,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsRow
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.Ticket.ID,
			&i.Ticket.Number,
			&i.Ticket.Subject,
			&i.Ticket.Status,
			&i.Ticket.Priority,
			&i.Ticket.RequesterID,
			&i.Ticket.AssigneeID,
			&i.Ticket.TeamID,
			&i.Ticket.CreatedAt,
			&i.Ticket.UpdatedAt,
			&i.Ticket.ClosedAt,
			&i.Ticket.SearchTsv,
			&i.RequesterName,
			&i.RequesterEmail,
			&i.AssigneeName,
			&i.AssigneeEmail,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTicketNumber = `-- name: NextTicketNumber :one

INSERT INTO ticket_number_counters (day, counter)
VALUES ($1::date, 1)
ON CONFLICT (day) DO UPDATE
SET counter = ticket_number_counters.counter + 1
RETURNING counter
`

// Tickets: M2 core. Number allocation, CRUD, filtered lists, FTS search,
// field updates (each RETURNING the row so the service can emit events),
// and dashboard counters.
// Race-free per-day sequence: the UPSERT takes a row lock on the day's
// counter, so concurrent allocations (any number of replicas) serialize
// and each caller gets a unique, gapless-within-commit value. Call inside
// the ticket-creating transaction so an aborted create at worst leaves a
// gap, never a duplicate.
func (q *Queries) NextTicketNumber(ctx context.Context, day time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, nextTicketNumber, day)
	var counter int32
	err := row.Scan(&counter)
	return counter, err
}

const searchTickets = `-- name: SearchTickets :many
WITH q AS (
    SELECT websearch_to_tsquery('english', $11::text) AS tsq
), hits AS (
    SELECT t.id AS ticket_id, ts_rank(t.search_tsv, q.tsq) AS rank
    FROM tickets t, q
    WHERE t.search_tsv @@ q.tsq
    UNION ALL
    SELECT a.ticket_id, ts_rank(a.search_tsv, q.tsq) AS rank
    FROM articles a, q
    WHERE a.search_tsv @@ q.tsq
), ranked AS (
    SELECT ticket_id, max(rank) AS rank
    FROM hits
    GROUP BY ticket_id
)
SELECT t.id, t.number, t.subject, t.status, t.priority, t.requester_id, t.assignee_id, t.team_id, t.created_at, t.updated_at, t.closed_at, t.search_tsv,
       requester.name  AS requester_name,
       requester.email AS requester_email,
       COALESCE(assignee.name, '')         AS assignee_name,
       COALESCE(assignee.email::text, '')  AS assignee_email,
       ranked.rank::real AS rank,
       count(*) OVER () AS total_count
FROM ranked
JOIN tickets t ON t.id = ranked.ticket_id
JOIN users requester ON requester.id = t.requester_id
LEFT JOIN users assignee ON assignee.id = t.assignee_id
WHERE (COALESCE(cardinality($1::text[]), 0) = 0 OR t.status::text = ANY ($1::text[]))
  AND (COALESCE(cardinality($2::text[]), 0) = 0 OR t.priority::text = ANY ($2::text[]))
  AND ($3::uuid IS NULL OR t.assignee_id = $3::uuid)
  AND (NOT COALESCE($4::boolean, false) OR t.assignee_id IS NULL)
  AND ($5::uuid IS NULL OR t.team_id = $5::uuid)
  AND ($6::uuid IS NULL OR t.requester_id = $6::uuid)
  AND ($7::uuid IS NULL OR EXISTS (
        SELECT 1 FROM ticket_tags tt
        WHERE tt.ticket_id = t.id AND tt.tag_id = $7::uuid))
  -- closed_today mirrors the DashboardCounts closed-today predicate so the
  -- dashboard tile can deep-link a queue that matches its number.
  AND (NOT COALESCE($8::boolean, false)
       OR (t.status = 'closed' AND t.closed_at >= date_trunc('day', now())))
ORDER BY ranked.rank DESC, t.updated_at DESC, t.id
LIMIT $10::bigint
OFFSET $9::bigint
`

type SearchTicketsParams struct {
	Statuses    []string    `json:"statuses"`
	Priorities  []string    `json:"priorities"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	Unassigned  pgtype.Bool `json:"unassigned"`
	TeamID      pgtype.UUID `json:"team_id"`
	RequesterID pgtype.UUID `json:"requester_id"`
	TagID       pgtype.UUID `json:"tag_id"`
	ClosedToday pgtype.Bool `json:"closed_today"`
	PageOffset  int64       `json:"page_offset"`
	PageLimit   int64       `json:"page_limit"`
	Query       string      `json:"query"`
}

type SearchTicketsRow struct {
	Ticket         Ticket      `json:"ticket"`
	RequesterName  string      `json:"requester_name"`
	RequesterEmail string      `json:"requester_email"`
	AssigneeName   string      `json:"assignee_name"`
	AssigneeEmail  interface{} `json:"assignee_email"`
	Rank           float32     `json:"rank"`
	TotalCount     int64       `json:"total_count"`
}

// Full-text search across ticket subjects AND article bodies: the two
// generated tsvector columns are matched separately, UNIONed, and ranked
// per ticket by the best-matching hit. Same filters as ListTickets so
// search composes with the fixed views.
func (q *Queries) SearchTickets(ctx context.Context, arg SearchTicketsParams) ([]SearchTicketsRow, error) {
	rows, err := q.db.Query(ctx, searchTickets,
		arg.Statuses,
		arg.Priorities,
		arg.AssigneeID,
		arg.Unassigned,
		arg.TeamID,
		arg.RequesterID,
		arg.TagID,
		arg.ClosedToday,
		arg.PageOffset,
		arg.PageLimit,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTicketsRow
	for rows.Next() {
		var i SearchTicketsRow
		if err := rows.Scan(
			&i.Ticket.ID,
			&i.Ticket.Number,
			&i.Ticket.Subject,
			&i.Ticket.Status,
			&i.Ticket.Priority,
			&i.Ticket.RequesterID,
			&i.Ticket.AssigneeID,
			&i.Ticket.TeamID,
			&i.Ticket.CreatedAt,
			&i.Ticket.UpdatedAt,
			&i.Ticket.ClosedAt,
			&i.Ticket.SearchTsv,
			&i.RequesterName,
			&i.RequesterEmail,
			&i.AssigneeName,
			&i.AssigneeEmail,
			&i.Rank,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTicket = `-- name: TouchTicket :one
UPDATE tickets
SET updated_at = now()
WHERE id = $1
RETURNING id, number, subject, status, priority, requester_id, assignee_id, team_id, created_at, updated_at, closed_at, search_tsv
`

// Bump updated_at (e.g. when an article arrives) and return the row.
func (q *Queries) TouchTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, touchTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.RequesterID,
		&i.AssigneeID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SearchTsv,
	)
	return i, err
}

const updateTicketAssignee = `-- name: UpdateTicketAssignee :one
UPDATE tickets
SET assignee_id = $2,
    updated_at  = now()
WHERE id = $1
RETURNING id, number, subject, status, priority, requester_id, assignee_id, team_id, created_at, updated_at, closed_at, search_tsv
`

type UpdateTicketAssigneeParams struct {
	ID         uuid.UUID   `json:"id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

func (q *Queries) UpdateTicketAssignee(ctx context.Context, arg UpdateTicketAssigneeParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketAssignee, arg.ID, arg.AssigneeID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.RequesterID,
		&i.AssigneeID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SearchTsv,
	)
	return i, err
}

const updateTicketPriority = `-- name: UpdateTicketPriority :one
UPDATE tickets
SET priority   = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, number, subject, status, priority, requester_id, assignee_id, team_id, created_at, updated_at, closed_at, search_tsv
`

type UpdateTicketPriorityParams struct {
	ID       uuid.UUID      `json:"id"`
	Priority TicketPriority `json:"priority"`
}

func (q *Queries) UpdateTicketPriority(ctx context.Context, arg UpdateTicketPriorityParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketPriority, arg.ID, arg.Priority)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.RequesterID,
		&i.AssigneeID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SearchTsv,
	)
	return i, err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets
SET status     = $1,
    closed_at  = CASE
                     WHEN $1::ticket_status = 'closed' THEN COALESCE(tickets.closed_at, now())
                     ELSE NULL
                 END,
    updated_at = now()
WHERE id = $2
RETURNING id, number, subject, status, priority, requester_id, assignee_id, team_id, created_at, updated_at, closed_at, search_tsv
`

type UpdateTicketStatusParams struct {
	Status TicketStatus `json:"status"`
	ID     uuid.UUID    `json:"id"`
}

// closed_at is stamped on the open->closed edge, preserved while closed,
// and cleared on reopen.
func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.Status, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.RequesterID,
		&i.AssigneeID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SearchTsv,
	)
	return i, err
}

const updateTicketTeam = `-- name: UpdateTicketTeam :one
UPDATE tickets
SET team_id    = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, number, subject, status, priority, requester_id, assignee_id, team_id, created_at, updated_at, closed_at, search_tsv
`

type UpdateTicketTeamParams struct {
	ID     uuid.UUID   `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) UpdateTicketTeam(ctx context.Context, arg UpdateTicketTeamParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketTeam, arg.ID, arg.TeamID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.RequesterID,
		&i.AssigneeID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.SearchTsv,
	)
	return i, err
}
