// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users
SET active     = true,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const adminExists = `-- name: AdminExists :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE role = 'admin' AND active
)::boolean AS admin_exists
`

func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, adminExists)
	var admin_exists bool
	err := row.Scan(&admin_exists)
	return admin_exists, err
}

const bumpUserTokenVersion = `-- name: BumpUserTokenVersion :one
UPDATE users
SET token_version = token_version + 1,
    updated_at    = now()
WHERE id = $1
RETURNING token_version
`

func (q *Queries) BumpUserTokenVersion(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpUserTokenVersion, id)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, role, password_hash, company)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, role, password_hash, oidc_issuer, oidc_subject, company, token_version, active, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	Role         UserRole    `json:"role"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Company      string      `json:"company"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.Company,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Company,
		&i.TokenVersion,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET active     = false,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const ensureUserByEmail = `-- name: EnsureUserByEmail :one
INSERT INTO users (email, name, role)
VALUES ($1, $2, 'customer')
ON CONFLICT (email) DO UPDATE
SET email = users.email
RETURNING id, email, name, role, password_hash, oidc_issuer, oidc_subject, company, token_version, active, created_at, updated_at
`

type EnsureUserByEmailParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// M3 inbound email: look up the sender by address (citext, so case folds),
// creating a CUSTOMER on first contact. The conflict arm is a deliberate
// no-op self-assignment: an existing user is returned unchanged — in
// particular their role — so an unknown sender can NEVER be auto-created
// as (or promoted to) agent/admin via email (architecture doc §4).
func (q *Queries) EnsureUserByEmail(ctx context.Context, arg EnsureUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureUserByEmail, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Company,
		&i.TokenVersion,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, password_hash, oidc_issuer, oidc_subject, company, token_version, active, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Company,
		&i.TokenVersion,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, name, role, password_hash, oidc_issuer, oidc_subject, company, token_version, active, created_at, updated_at FROM users
WHERE id = $1
`

// Users: M1 CRUD.
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Company,
		&i.TokenVersion,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, password_hash, oidc_issuer, oidc_subject, company, token_version, active, created_at, updated_at FROM users
WHERE ($1::user_role IS NULL OR role = $1::user_role)
  AND ($2::boolean IS NULL OR active = $2::boolean)
  AND ($3::text IS NULL
       OR email ILIKE '%' || $3::text || '%'
       OR name ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC, id
LIMIT $5::bigint
OFFSET $4::bigint
`

type ListUsersParams struct {
	Role       NullUserRole `json:"role"`
	Active     pgtype.Bool  `json:"active"`
	Q          pgtype.Text  `json:"q"`
	PageOffset int64        `json:"page_offset"`
	PageLimit  int64        `json:"page_limit"`
}

// q is a substring match on email/name; callers must escape ILIKE
// wildcards (% _ \) in it first.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Role,
		arg.Active,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.OidcIssuer,
			&i.OidcSubject,
			&i.Company,
			&i.TokenVersion,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at    = now()
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name       = $2,
    role       = $3,
    company    = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, email, name, role, password_hash, oidc_issuer, oidc_subject, company, token_version, active, created_at, updated_at
`

type UpdateUserParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Role    UserRole  `json:"role"`
	Company string    `json:"company"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Company,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Company,
		&i.TokenVersion,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdmin = `-- name: UpsertAdmin :one
INSERT INTO users (email, name, role, password_hash)
VALUES ($1, $2, 'admin', $3)
ON CONFLICT (email) DO UPDATE
SET name          = CASE WHEN EXCLUDED.name <> '' THEN EXCLUDED.name ELSE users.name END,
    role          = 'admin',
    password_hash = EXCLUDED.password_hash,
    active        = true,
    -- Resetting the password revokes every outstanding session, matching
    -- the PATCH /users password path (admin create is the recovery path).
    token_version = users.token_version + 1,
    updated_at    = now()
RETURNING id, email, name, role, password_hash, oidc_issuer, oidc_subject, company, token_version, active, created_at, updated_at
`

type UpsertAdminParams struct {
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertAdmin, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Company,
		&i.TokenVersion,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
