// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, webhook_id, event_type, ticket_id, payload, status, response_code, attempts, last_error, created_at, delivered_at FROM webhook_deliveries
WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id int64) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.TicketID,
		&i.Payload,
		&i.Status,
		&i.ResponseCode,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one

INSERT INTO webhook_deliveries (webhook_id, event_type, ticket_id, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, webhook_id, event_type, ticket_id, payload, status, response_code, attempts, last_error, created_at, delivered_at
`

type InsertWebhookDeliveryParams struct {
	WebhookID uuid.UUID   `json:"webhook_id"`
	EventType string      `json:"event_type"`
	TicketID  pgtype.UUID `json:"ticket_id"`
	Payload   []byte      `json:"payload"`
}

// Webhook deliveries: the durable outbox log (M4). A row is inserted
// 'pending' in the same transaction as the ticket_event that spawned it; a
// River job then attempts HTTP delivery and records the outcome. Attempts is
// incremented on every terminal or intermediate outcome so the delivery log
// reflects River's retry count.
// Enqueue a pending delivery (status defaults to 'pending', attempts 0).
func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.WebhookID,
		arg.EventType,
		arg.TicketID,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.TicketID,
		&i.Payload,
		&i.Status,
		&i.ResponseCode,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const listRecentWebhookDeliveries = `-- name: ListRecentWebhookDeliveries :many
SELECT id, webhook_id, event_type, ticket_id, payload, status, response_code, attempts, last_error, created_at, delivered_at FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListRecentWebhookDeliveriesParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
}

// Admin delivery log for one endpoint, newest first.
func (q *Queries) ListRecentWebhookDeliveries(ctx context.Context, arg ListRecentWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listRecentWebhookDeliveries, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.TicketID,
			&i.Payload,
			&i.Status,
			&i.ResponseCode,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :exec
UPDATE webhook_deliveries
SET status        = 'failed',
    response_code = $2,
    attempts      = attempts + 1,
    last_error    = $3
WHERE id = $1
`

type MarkWebhookDeliveryFailedParams struct {
	ID           int64       `json:"id"`
	ResponseCode pgtype.Int4 `json:"response_code"`
	LastError    pgtype.Text `json:"last_error"`
}

// Terminal failure: River has exhausted its retries. response_code is null
// for transport-level errors (no HTTP response).
func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryFailed, arg.ID, arg.ResponseCode, arg.LastError)
	return err
}

const markWebhookDeliverySuccess = `-- name: MarkWebhookDeliverySuccess :exec
UPDATE webhook_deliveries
SET status        = 'success',
    response_code = $2,
    attempts      = attempts + 1,
    last_error    = NULL,
    delivered_at  = now()
WHERE id = $1
`

type MarkWebhookDeliverySuccessParams struct {
	ID           int64       `json:"id"`
	ResponseCode pgtype.Int4 `json:"response_code"`
}

// Terminal success: 2xx received. Stamp delivered_at, clear any prior error.
func (q *Queries) MarkWebhookDeliverySuccess(ctx context.Context, arg MarkWebhookDeliverySuccessParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliverySuccess, arg.ID, arg.ResponseCode)
	return err
}

const recordWebhookDeliveryRetry = `-- name: RecordWebhookDeliveryRetry :exec
UPDATE webhook_deliveries
SET status        = 'pending',
    response_code = $2,
    attempts      = attempts + 1,
    last_error    = $3
WHERE id = $1
`

type RecordWebhookDeliveryRetryParams struct {
	ID           int64       `json:"id"`
	ResponseCode pgtype.Int4 `json:"response_code"`
	LastError    pgtype.Text `json:"last_error"`
}

// Intermediate failure with a retry still scheduled: keep status 'pending',
// but bump attempts and record the latest error/code so the log shows
// progress between River attempts (avoids a spurious failed->success flip).
func (q *Queries) RecordWebhookDeliveryRetry(ctx context.Context, arg RecordWebhookDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, recordWebhookDeliveryRetry, arg.ID, arg.ResponseCode, arg.LastError)
	return err
}
