// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createWebhook = `-- name: CreateWebhook :one

INSERT INTO webhooks (name, url, secret_enc, events, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, url, secret_enc, events, active, created_at, updated_at
`

type CreateWebhookParams struct {
	Name      string   `json:"name"`
	Url       string   `json:"url"`
	SecretEnc string   `json:"secret_enc"`
	Events    []string `json:"events"`
	Active    bool     `json:"active"`
}

// Webhooks: outbound HTTP endpoints (M4). secret_enc holds the AES-GCM
// ciphertext of the per-endpoint HMAC signing secret (secrets package,
// purpose "webhook-secret"); it is written and read as opaque text here.
func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.Name,
		arg.Url,
		arg.SecretEnc,
		arg.Events,
		arg.Active,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM webhooks
WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, name, url, secret_enc, events, active, created_at, updated_at FROM webhooks
WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhooksByEvent = `-- name: ListActiveWebhooksByEvent :many
SELECT id, name, url, secret_enc, events, active, created_at, updated_at FROM webhooks
WHERE active
  AND $1::text = ANY (events)
ORDER BY id
`

// The delivery fan-out: every active endpoint subscribed to this event type.
// Drives transactional enqueue of webhook_deliveries off a ticket_event.
func (q *Queries) ListActiveWebhooksByEvent(ctx context.Context, dollar_1 string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksByEvent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.SecretEnc,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, name, url, secret_enc, events, active, created_at, updated_at FROM webhooks
ORDER BY created_at DESC, id
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.SecretEnc,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET name       = $2,
    url        = $3,
    secret_enc = $4,
    events     = $5,
    active     = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, url, secret_enc, events, active, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Url       string    `json:"url"`
	SecretEnc string    `json:"secret_enc"`
	Events    []string  `json:"events"`
	Active    bool      `json:"active"`
}

// Full-row config update. Callers pass the existing secret_enc unchanged when
// the signing secret was not rotated.
func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.SecretEnc,
		arg.Events,
		arg.Active,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.SecretEnc,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
