/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthUsersRouteImport } from './routes/_auth.users'
import { Route as AuthTicketsRouteImport } from './routes/_auth.tickets'
import { Route as AuthTeamsRouteImport } from './routes/_auth.teams'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthTicketsIndexRouteImport } from './routes/_auth.tickets.index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth.settings.index'
import { Route as AuthTicketsTicketIdRouteImport } from './routes/_auth.tickets.$ticketId'
import { Route as AuthSettingsMailboxesRouteImport } from './routes/_auth.settings.mailboxes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTicketsRoute = AuthTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamsRoute = AuthTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTicketsIndexRoute = AuthTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTicketsRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthTicketsTicketIdRoute = AuthTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AuthTicketsRoute,
} as any)
const AuthSettingsMailboxesRoute = AuthSettingsMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AuthSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/teams': typeof AuthTeamsRoute
  '/tickets': typeof AuthTicketsRouteWithChildren
  '/users': typeof AuthUsersRoute
  '/settings/mailboxes': typeof AuthSettingsMailboxesRoute
  '/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/tickets/': typeof AuthTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/teams': typeof AuthTeamsRoute
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
  '/settings/mailboxes': typeof AuthSettingsMailboxesRoute
  '/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/tickets': typeof AuthTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/teams': typeof AuthTeamsRoute
  '/_auth/tickets': typeof AuthTicketsRouteWithChildren
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/settings/mailboxes': typeof AuthSettingsMailboxesRoute
  '/_auth/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/tickets/': typeof AuthTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/teams'
    | '/tickets'
    | '/users'
    | '/settings/mailboxes'
    | '/tickets/$ticketId'
    | '/settings/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/teams'
    | '/users'
    | '/'
    | '/settings/mailboxes'
    | '/tickets/$ticketId'
    | '/settings'
    | '/tickets'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/_auth/teams'
    | '/_auth/tickets'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/settings/mailboxes'
    | '/_auth/tickets/$ticketId'
    | '/_auth/settings/'
    | '/_auth/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tickets': {
      id: '/_auth/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthTicketsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teams': {
      id: '/_auth/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthTeamsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tickets/': {
      id: '/_auth/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthTicketsIndexRouteImport
      parentRoute: typeof AuthTicketsRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/tickets/$ticketId': {
      id: '/_auth/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthTicketsTicketIdRouteImport
      parentRoute: typeof AuthTicketsRoute
    }
    '/_auth/settings/mailboxes': {
      id: '/_auth/settings/mailboxes'
      path: '/mailboxes'
      fullPath: '/settings/mailboxes'
      preLoaderRoute: typeof AuthSettingsMailboxesRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
  }
}

interface AuthSettingsRouteChildren {
  AuthSettingsMailboxesRoute: typeof AuthSettingsMailboxesRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsMailboxesRoute: AuthSettingsMailboxesRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthTicketsRouteChildren {
  AuthTicketsTicketIdRoute: typeof AuthTicketsTicketIdRoute
  AuthTicketsIndexRoute: typeof AuthTicketsIndexRoute
}

const AuthTicketsRouteChildren: AuthTicketsRouteChildren = {
  AuthTicketsTicketIdRoute: AuthTicketsTicketIdRoute,
  AuthTicketsIndexRoute: AuthTicketsIndexRoute,
}

const AuthTicketsRouteWithChildren = AuthTicketsRoute._addFileChildren(
  AuthTicketsRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthTeamsRoute: typeof AuthTeamsRoute
  AuthTicketsRoute: typeof AuthTicketsRouteWithChildren
  AuthUsersRoute: typeof AuthUsersRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthTeamsRoute: AuthTeamsRoute,
  AuthTicketsRoute: AuthTicketsRouteWithChildren,
  AuthUsersRoute: AuthUsersRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
